- build/actions.sh
Removes some assumptions about the environment.
> Build fixes

- web/table/csv2html.py
https://travis-ci.org/oilshell/oil/jobs/336386811#L513-L515
> Fix undefined name: print the exception

- core/args.py
https://travis-ci.org/oilshell/oil/jobs/336386811#L477-L482
> Fix undefined name: short_flag --> short_name * 2

- bin/oil.py
- core/builtin.py
- core/cmd_exec.py
- core/cmd_exec_test.py
- core/state.py
- spec/builtins.test.sh
- test/spec.sh
> Implement set -o vi/emacs

- core/builtin.py
- spec/assign.test.sh
This pr completes `declare -F`.
> Adding Declare -F To Builtins

- core/word_eval.py
- spec/array.test.sh
Resolves spec test "Retrieve all indices with !" in array and introduces spec test "Retrieve all sparse indices with !".
> Implement array index arrays with ! (#153)

- core/builtin.py
Followup from a comment on #209 .
> [printf] Add explanatory comment on %q implementation.

- build/dev.sh
Fixes #216 (and removes a manual step from the "contribution" instructions)
> Create _tmp dir automatically

- core/ui.py
Hello,
Since I've seen no import of `os.path` in core, I switched pylib's os_path...
> add support for \W in $PS1

- osh/builtin.py
- osh/cmd_exec.py
- osh/runtime.asdl
- spec/builtins2.test.sh
add spec tests for
- builtin x when a function called x exists
- builtin for an invalid command
- builtin without arguments
see https://github.com/oilshell/oil/issues/146 for details
> add 'builtin' builtin

- core/comp_ui.py
- core/comp_ui_test.py
- osh/prompt.py
- osh/prompt_test.py
Closes https://github.com/oilshell/oil/issues/252
> Fix readline problems

- osh/builtin.py
- spec/builtin-bash.test.sh
addresses https://github.com/oilshell/oil/issues/259
if found:
if file, print the filename
otherwise do nothing
otherwise, set status to 1
add unit tests for type -p builtin
> add -p option to type builtin

- core/comp_ui.py
- native/libc.c
- native/libc_test.py
Addresses #269. Since the release build of python doesn't support unicode, we have to use C libraries to decode to and from it.
> Take unicode into account when calculating display width

- core/process.py
- osh/builtin.py
- spec/command_.test.sh
- test/spec.sh
Resolve the full filepath since it might be a command in PATH, not the current directory.
> Run files with /bin/sh if shebang is missing

- osh/word.py
Addresses https://github.com/oilshell/oil/issues/364
> Add location information for ~

- core/comp_ui.py
- core/comp_ui_test.py
- native/libc_test.py
Addresses https://github.com/oilshell/oil/issues/394#issuecomment-508942298
> Allow prompts to contain newline

- build/compile.sh
- configure
See https://github.com/oilshell/oil/pull/411#issuecomment-509020340 and https://github.com/oilshell/oil/issues/415#issuecomment-509854207 for discussion.
> Add changes to ./configure to build on FreeBSD

- configure
- install
Hi Andy,
first draft. I added the `$DESTDIR` stuff, ignored a good bunch of common `configure` arguments and cleaned up various other stuff I found. As usual feel free to cherry-pick and/or comment.
> ./configure and $DESTDIR

- configure
Make configure a bit more specific about what options expect arguments and how they relate.
> [configure] better usage message

- doc/architecture-notes.md
(Also some punctuation tweaks.)
> Fix a typo and capitalization of section titles

- osh/builtin_printf.py
- spec/builtin-printf.test.sh
> [spec/builtin-printf] Implement printf %d \'c to print the numeric value of char c

- frontend/location.py
- types/run.sh
Also add it to travis checks to prevent regressions.
@andychu did I do it right with "UP_node"?  What does UP stand for, anyway?  Union... Parameter?
> [types] get frontend/location.py passing with mypy

- osh/split.py
- osh/state.py
- types/more-oil-manifest.txt
> Get osh/split.py type checked

- Makefile
- build/compile.sh
- uninstall
This is the PR mentioned in the zulip thread ['Adding an uninstall script'](https://oilshell.zulipchat.com/#narrow/stream/121539-oil-dev/topic/Adding.20an.20uninstall.20script).
> [devtools] Add uninstall script akin to the install script

- oil_lang/objects.py
- osh/cmd_exec.py
- types/more-oil-manifest.txt
I'm unsure about some of these.  I used `Any` in several places, some
of which can probably be more specific.  It'll probably need
revisiting, but it's a step in the right direction, I hope.
> [types] Add type annotations for oil_lang/objects.py [tentative]

- osh/cmd_exec.py
- osh/state.py
- spec/builtin-completion.test.sh
- spec/special-vars.test.sh
- types/run.sh
@andychu let me know what you think of these.
> Assorted fixes, etc.   Aftermath of type-checking osh/cmd_exec.py

- oil_lang/expr_eval.py
- osh/cmd_exec.py
- osh/expr_eval.py
- osh/state.py
- osh/word_.py
- osh/word_eval.py
- types/more-oil-manifest.txt
This went ok.  I'm getting the hang of it, I think.  I used "Any" in a few places that seemed appropriate.  Also had to add some `assert isinstance(<var>, <type>)` statements to make mypy happy.
> [types] add type annotations to osh/word_eval.py

- bin/oil.py
- osh/builtin.py
- osh/runtime.asdl
- spec/builtin-times.test.sh
- test/spec.sh
> WIP: Implements `times` builtin

- spec/builtin-dirs.test.sh
`popd` should return status code 1
> Spec test: `popd` empty directory stack

- shell.nix
Addresses improvement suggested by @Fridh in code review on #599.
> use nix idiom for shared lib extension

- native/libc_test.py
Fixes #611. I went ahead and guarded just the specific test cases that fail.
> skip libc tests that fail on darwin/macOS

- doc/help.md
Oops sorry I did a `git push -f` to master ... obliterating the earlier merge.  Trying again.
> help.md: add lost backticks

- spec/nocasematch-match.test.sh
- test/spec.sh
I wasn't entirely sure what to put, but I figured it would be better to be too thorough than not thorough enough.
> [test/spec] Spec tests for nocasematch

- osh/sh_expr_eval.py
- spec/ble-features.test.sh
> [arith] Fix scalar lvalue of arrays (compat_array).

- doc/idioms.md
Some broken variable references I noticed.
> fix nonexisiting variable references

- doc/help.md
I just wanted to check your opinion on these changes. I've tried to make texts as short and concise as possible, and I have tried to mark as unimplemented those that I _think_ they are.
The spec tests have been helpful, as you told me.
> Improve echo, read, mapfile documentation

- frontend/id_kind_def.py
- frontend/lexer_def.py
- frontend/syntax.asdl
- oil_lang/expr_to_ast.py
- oil_lang/grammar.pgen2
- tea/testdata/loops.tea
- Implement 'for' statements in the grammar
- Support CST->AST conversion for loops (while/for)
- Add 'break'/'continue'/'return' as tea keywords.
> [tea] Support AST generation for loops

- oil_lang/testdata/tour.oil
I started on a tour of oil path.
It's a .sh file to be executable. I thought that way it could be embedded into learnXinY
I'm open about the format.
This is an initial PR, not everything is included for sure.
Feel free to nitpick on anything, I don't mind changing wording or format.
Hopefully this gets the discussion going.
References that should probably be included
https://www.oilshell.org/release/latest/doc/eggex.html
https://www.oilshell.org/release/latest/doc/idioms.html
https://www.oilshell.org/release/latest/doc/oil-help.html
missing topics
- read
- write
- test
Documents that can provide inspiration
https://learnxinyminutes.com/docs/tcsh/
https://learnxinyminutes.com/docs/bash/
fixes https://github.com/oilshell/oil/issues/934
Idea
- I quite like the `putting it together` part at …
> initial add of tour of oil

- doc/oil-language-tour.md
> Fix small example in language tour

- types/common.sh
> Use system mypy if it is the only option

- core/process.py
- frontend/flag_def.py
- osh/builtin_process.py
- spec/background.test.sh
Support for `jobs -p`, aiming to close #1017 .
> Add support for jobs -p

- .gitignore
- build/native.sh
- mycpp/common.h
- mycpp/gc_heap.cc
- mycpp/gc_heap.h
- mycpp/my_runtime.cc
- mycpp/mylib.h
Just some random comments.  Any thoughts on the following @andychu ?
> Change out some assert(0) for InvalidCodePath() and add comments

- cpp/time_.h
> Fix off by one

- mycpp/gc_heap.h
Caught by ubsan:
/home/c/dev/oil/mycpp/gc_heap.h:972:47: runtime error: member access within
null pointer of type 'Slab<int>'
Previously, List::reserve() was copying from the old slab to the new one
whenever the *newly updated* capacity was greater than zero. If the
capacity was previously zero, slab_ might be nullptr.
Now it copies only when the list is non-empty.
> [fix] Fix nullptr deref in List::reserve()

- cpp/leaky_posix.h
Now posix::execve() converts and forwards its environ argument to execve.
Reduces the spec-cpp delta cpp number by 26 (70 to 44) if I ran the tests correctly.
> Pass the environment to execve()

- mycpp/my_runtime.cc
https://github.com/oilshell/oil/pull/1234
Original PR here ^
Opening a new one because it's easier than taking all the spurious changes out of that one.
> Fix invalid writes in Str::split

- cpp/NINJA-steps.sh
- mycpp/gc_heap.cc
- mycpp/gc_heap.h
- mycpp/gc_heap_test.cc
- test/baseline.spec-cpp.assertion_fails
Same change as before.  Doesn't crash anymore
> Redo mmap tricks

- .github/workflows/all-builds.yml
- benchmarks/auto.sh
- benchmarks/report.sh
- deps/Dockerfile.cpp
- deps/images.sh
- mycpp/TEST.sh
- soil/host-shim.sh
- soil/web-remote.sh
- soil/worker.sh
Also make note of github actions thing
TESTING GITHUB ACTIONS
> preparing to put mycpp/examples R report in CI

- mycpp/leaky_mylib.cc
- mycpp/leaky_mylib.h
This CL encapsulates the data for `BufWriter` into a separate `Buf` class.
> Add `Buf` class to `BufWriter`

- cpp/leaky_core.cc
> [cpp] remove some calls to malloc()

- frontend/signal_gen.py
> [frontend] fix bogus signal values

- build/dynamic-deps.sh
- core/shell_native.py
- cpp/leaky_core_error.h
- cpp/leaky_stdlib.cc
- cpp/leaky_stdlib.h
- osh/builtin_process.py
- prebuilt/dynamic-deps/filter-translate.txt
Just needed a few small fixes to make `builtin_process.py` translatable to get this working
> add job control to oil-native

- mycpp/gc_dict.h
- mycpp/gc_list.h
> [mycpp] add some missing member initializers

- mycpp/gc_str.cc
- mycpp/gc_str.h
- mycpp/gc_str_test.cc
Some yet-to-be-translated code uses this.
> [mycpp] add maxsplits flavor for Str::split()

- bin/NINJA_subgraph.py
- build/c_module_srcs.py
- build/ninja_main.py
- cpp/NINJA_subgraph.py
- cpp/fanos.cc
- cpp/fanos.h
- cpp/fanos_shared.c
- cpp/fanos_shared.h
- mycpp/gc_builtins.h
- pyext/fanos.c
- pyext/setup_fanos.py
- test/lint.sh
A future commit will need this change to make core/main_loop.py translatable.
> [translation] share fanos between C++ and pyext

- cpp/pylib.cc
- cpp/pylib.h
- cpp/pylib_test.cc
We'll need this to translate the completion spec.
> [cpp/pylib] add path_stat::isdir()

- core/completion.py
- core/pyos.py
- cpp/core.cc
- cpp/core.h
- cpp/core_test.cc
We'll use this in place of python's pwd.getpwall() in core/completion.py
> [cpp/core] add PasswdEntry, GetAllUsers()

- cpp/core.cc
- cpp/core.h
- cpp/core_test.cc
mycpp generates code that uses pointers at the call sites for this function.
> [cpp] return managed Tuple from MakeDirCacheKey()

- mycpp/comparators.h
- mycpp/gc_builtins.cc
- mycpp/gc_builtins.h
- mycpp/gc_dict.h
- mycpp/gc_dict_test.cc
- mycpp/gc_list.h
- mycpp/gc_list_test.cc
There are a few builtins and data structure methods used throughout the completion code that aren't yet supported in the runtime. This series of commits adds them.
> [mycpp] add data structure builtins for completion

- core/state.py
- osh/cmd_eval.py
Not sure what you'd like in terms of commit message :)
> [refactor] CurrentSpanId#int -> CurrentLocation#loc_t

- mycpp/gc_builtins.cc
- mycpp/gc_builtins.h
- mycpp/gc_list.h
- mycpp/gc_str.cc
- mycpp/gc_str_test.cc
A few things to match python's behavior for some builtins. The negative width format string one is probably the most interesting change
> [mycpp] a few small changes for C++ readline

- NINJA-config.sh
- build/ninja-rules-cpp.sh
- core/comp_ui.py
- core/completion.py
- core/shell.py
- cpp/frontend_pyreadline.cc
- cpp/frontend_pyreadline.h
- mycpp/gc_list.h
This is the last big PR of the interactive shell series! This targets readline >= 4.0 on linux for now. I figure we can graft on the cross-platform stuff from cpython in smaller PRs when they become more pressing
> [translation] implement c++ readline stubs

- core/completion.py
- cpp/pylib.cc
Introduced in 78ca6b96f9e84e86899b3d6aeb908c39304dea95
> [completion] fix file system action trailing slash regression

- cpp/core.cc
this should reduce the delta on `spec/builtin-io`.
> [cpp] implement pyos::InputAvailable()

- asdl/gen_cpp.py
- mycpp/gc_obj.h
> [asdl] Reorder member variables of generated c++ types

- configure
- configure-test.sh
> Fix --readline handling and datarootdir fallback

- shell.nix
> [build] fix nix-shell 'clean' command

- core/shell.py
- doc/osh-help.md
- frontend/args_test.py
- frontend/flag_def.py
- spec/interactive.test.sh
Idk what you want in the commit message, i hope it's not too verbose 😛
> Implement --norc flag

- .github/workflows/all-builds.yml
- soil/github-actions.sh
- soil/web-init.sh
- soil/web.py
I'm not sure if this even works, how do you test this stuff?
> [soil] Add a link to the PR (if any) to the build index

- core/executor.py
- core/process.py
- core/process_test.py
- core/runtime.asdl
- core/vm.py
- frontend/parse_lib.py
- frontend/syntax.asdl
- oil_lang/expr_to_ast.py
- osh/cmd_eval.py
- osh/cmd_parse.py
- osh/word_.py
- osh/word_parse.py
- tools/osh2oil.py
> [rename] qsn_/ -> data_lang/

- oil_lang/expr_eval.py
Didn't get to these before the last patch merged.
> [oil_lang] some binary expression tweaks

- build/ninja-rules-cpp.sh
> Use READLINE_DIR value in flags in ninja-rules-cpp

- build/deps.sh
- build/dev-shell.sh
- deps/from-apt.sh
- deps/images.sh
- soil/host-shim.sh
Freshen up; make sure the code isn't stale
> [soil] Rebuild soil-{dummy,pea,wild} images

- core/shell.py
- frontend/flag_def.py
- osh/builtin_meta.py
- spec/ysh-source.test.sh
- stdlib/math.ysh
- test/spec.sh
One issue I have left to iron out is what happens when we call this from OSH?
Right now we get a syntax error, but I wonder if we should just outright ban `source --builtin` from OSH?
> [ysh] Add --builtin flag to source

- core/code.py
- core/vm.py
- frontend/typed_args.py
- library/func_eggex.py
- library/func_hay.py
- library/func_misc.py
- ysh/expr_eval.py
This will help us produce better errors in the future.
Figured I should send this before we add too many more functions
> [core/vm] simplify _Callable.Call() signature

- cpp/core.cc
Fixes: https://github.com/oilshell/oil/issues/1727
> [macos] Fix build failure due to missing std::fmod

- core/shell.py
- doc/ref/chap-type-method.md
- doc/ref/toc-ysh.md
- library/func_misc.py
- spec/ysh-methods.test.sh
I am making some progress on the argument parser. While doing that I found that I needed `List->join`.
> [ysh] List->join

- asdl/gen_cpp_test.cc
- core/optview_gen.py
- cpp/core.cc
- cpp/core_test.cc
- cpp/frontend_match_test.cc
- cpp/libc_test.cc
- cpp/stdlib.cc
- frontend/flag_gen.py
- mycpp/cppgen_pass.py
- mycpp/gc_builtins.cc
- mycpp/gc_dict.h
- mycpp/gc_dict_test.cc
- mycpp/gc_list.h
- mycpp/gc_list_test.cc
- mycpp/gc_str.cc
- mycpp/gc_str.h
- mycpp/gc_str_test.cc
- mycpp/mark_sweep_heap_test.cc
- prebuilt/frontend/args.mycpp.cc
This will make some refactoring and renaming Dict possible.
> rename index_() to at()

- osh/cmd_eval.py
This should reduce unnecessary rooting by a lot
> [osh/cmd_eval] decompose _Dispatch()

- spec/builtin-bash.test.sh
Partially addresses issue #259.
Possibly not good practice to open this before I've addressed the comments on the `shopt -s nocasematch` PR, but writing these spec tests was more relaxing than most things I could do. Hopefully they're useful.
> [test/spec] Spec tests for type -a

- README.md
The directory was renamed in commit acbe70b27
> [README] library -> builtin

- frontend/id_kind_def.py
- frontend/lexer_def.py
- spec/ysh-expr.test.sh
- ysh/expr_parse.py
- ysh/expr_to_ast.py
- ysh/grammar.pgen2
I decided to implement this in a PR separate from https://github.com/oilshell/oil/pull/1778.
> [ysh] Make ^"..." syntax sugar for ^["..."]

- mycpp/README.md
I got this working on my machine with this small change.
> fix README.md

- cpp/stdlib.cc
> reduce calls to malloc before execve()

- mycpp/pass_state.py
- mycpp/pass_state_test.py
Found some gaps while using this to generate a CFG for mycpp/examples/control_flow.py. This commit fills in those holes and adds some tests.
This also gets rid of the awkward `SetBranchExits()` thing.
> mycpp: generalize blocks and other cfg tweaks

- mycpp/ast_pass.py
- mycpp/control_flow_pass.py
- mycpp/cppgen_pass.py
- mycpp/ir_pass.py
- mycpp/mycpp_main.py
- mycpp/pass_state.py
- mycpp/util.py
- mycpp/visitor.py
- prebuilt/ninja/mycpp.mycpp_main/deps.txt
This commit adds the first concrete `Fact` and uses it to annotate statements that make function calls. You can feed this in to `_bin/datalog/call-graph` and see a list of statements that might lead to the GC being invoked. This output still doesn't impact the generated C++, though.
> [mycpp] annotate CFG with function calls

- doc/ref/toc-ysh.md
i'm guessing this should be .html? but also these links dont work from markdown :( i'm only guessing this works
> add .html to header link toc-ysh.md

- mycpp/examples/gc_stack_roots.py
This test will be a helpful way to track the stack roots optimization work.
> [mycpp] add example to illustrate rooting scenarios

- builtin/method_str.py
- core/shell.py
- doc/ref/chap-type-method.md
- spec/ysh-builtin-eval.test.sh
- spec/ysh-methods.test.sh
See design discussion on zulip: https://oilshell.zulipchat.com/#narrow/stream/447377-api-design/topic/API.20design.20-.20shSplit.28.29.20split.28.29.20splitlines.28.29
TODOs:
> Implement `string.split()`

- builtin/trap_osh.py
- spec/builtin-trap.test.sh
The POSIX specification requires this.
I also added a spec test.
Fixes 2055
> [builtin/trap] Reset condition on unsigned-integer

- ysh/val_ops.py
https://oilshell.zulipchat.com/#narrow/channel/121539-oil-dev/topic/2024-11-22.20Meeting/near/484160203
> [ysh/val_opts] Fix typos in cast destination types

- osh/sh_expr_eval.py
- spec/array.test.sh
https://github.com/oils-for-unix/oils/pull/2138#discussion_r1855493290
> [osh/sh_expr_eval] Tell valid index range for out-of-range `[[ -v a[i] ]]`

- osh/cmd_eval.py
- spec/array.test.sh
https://oilshell.zulipchat.com/#narrow/channel/121539-oil-dev/topic/2024-11-22.20Meeting/near/485165500
> [osh] change BashArray `a+=()` to modify existing instance

- osh/cmd_eval.py
- spec/assoc.test.sh
- spec/ysh-with-sh.test.sh
https://oilshell.zulipchat.com/#narrow/channel/121539-oil-dev/topic/2024-11-22.20Meeting/near/485167138
> [osh] Implement BashAssoc `assoc+=()`

- core/bash_impl.py
- osh/cmd_eval.py
https://oilshell.zulipchat.com/#narrow/channel/121539-oil-dev/topic/2024-11-22.20Meeting/near/485167553
> [refactor] Add `Bash{Array,Assoc}_{Get,Append}Values` for `+=`

- builtin/assign_osh.py
- core/bash_impl.py
- osh/cmd_eval.py
- spec/ble-idioms.test.sh
https://oilshell.zulipchat.com/#narrow/channel/121539-oil-dev/topic/2024-11-22.20Meeting/near/485084833
> [osh] Support `sp+=(...)` for `SparseArray`

- core/bash_impl.py
- core/state.py
This moves the codes into `core/bash_impl.py`.
> [core refactor] Refactor the code for BashArray/BashAssoc `a[i]=v`

- builtin/pure_ysh.py
- core/bash_impl.py
- ysh/val_ops.py
- Commit 0748e09ab8d4ae7d22905c17d5ee4b81d31f607e: `append ... (a)` for BashArray
- Commit 7721ce2e3c96d794155279d4ca23e190a1cef6fe: `$[a1 == a2]` for BashArray/BashAssoc
- Commit 9157bcccd08d4f043b5dec7c0c98a9e68ed38cbf: `$[bool(a)]` for BashArray/BashAssoc
> [ysh refactor] Refactor BashArray/BashAssoc `append`, `===`, and `bool`

- frontend/syntax.asdl
- frontend/syntax_abbrev.py
- osh/cmd_eval_test.py
- osh/word_eval.py
- osh/word_parse.py
- osh/word_parse_test.py
- tools/ysh_ify.py
https://github.com/oils-for-unix/oils/pull/2200#discussion_r1897040894
> [syntax refactor] rename "BracedVarSub.{token => name_tok}"

- core/error.py
- osh/cmd_eval.py
- osh/word_eval.py
- spec/var-ref.test.sh
9386e2037 for https://github.com/oils-for-unix/oils/pull/2201#discussion_r1897976186
d304456bf for https://github.com/oils-for-unix/oils/pull/2201#discussion_r1897976947
> [osh] Make ${!ref} with invalid ref non-fatal

- data_lang/j8.py
- display/pp_value.py
This PR refactors the printing codes (j8 and pp_value) to use `bash_impl` instead of directly manipulating the internal representation of BashArray/SparseArray/BashAssoc.
> [refactor] Use `bash_impl` to print arrays

- osh/word_eval.py
- spec/assoc.test.sh
This PR also contains refactoring of `_DecayArray` (which is renamed to `_JoinArray` in this PR).
> [osh/word_eval] Implement BashAssoc `${a[*]}`

- osh/word_eval.py
- spec/ble-idioms.test.sh
As far as I recognize now, this is the last piece.
> [osh] Implement SparseArray `"${sp[*]}"`

- build/native.sh
- deps/Dockerfile.soil-bloaty
- deps/Dockerfile.soil-cpp-small
- deps/Dockerfile.soil-cpp-spec
- deps/from-apt.sh
- metrics/native-code.sh
- soil/cpp-tarball.sh
- soil/host-shim.sh
This goes in 'py3-libs', which is not a wedge yet
> [deps] Rebuild soil-benchmarks wedge with new 'pyte' library

- builtin/process_osh.py
- core/process.py
- doc/ref/chap-option.md
- frontend/option_def.py
- spec/ysh-options.test.sh
I hope the `not None` to safe a nested `if` is OK. 😇
> hide "but oils didn't start it" behind xtrace

- doc/ref/chap-option.md
https://github.com/koalaman/shellcheck/issues/2555
> [chap-option.md] pipefail is posix

- core/executor.py
- cpp/pylib.cc
- cpp/pylib.h
- cpp/pylib_test.cc
- pylib/path_stat.py
- pylib/path_stat_test.py
- spec/builtin-eval-source.test.sh
- spec/command_.test.sh
- spec/divergence.test.sh
Changes:
- I discovered and added a failing test for https://github.com/oils-for-unix/oils/issues/2445
- Added a failing test for https://github.com/oils-for-unix/oils/issues/2429 and it's extension to `source`
- Fixed https://github.com/oils-for-unix/oils/issues/2429 and the related issue with `source`
> Fix: OSH tries to execute directories on PATH
