build.sh

As documented [here](https://www.reddit.com/r/oilshell/comments/5xfyg0/if_you_have_debianubuntu_a_web_server_and_five/), I discovered that the bash builtin `time` on Ubuntu 14.04 does not work like the time binary from apt. This adds `time` as a dependency.

Adding `time` to the list of dependencies

---

build.sh

`build.sh` has a hardcoded `x86_64`. Replacing it with a call to `$(uname -m)` means that at least some of the tests pass on `armv6l`.

Use $(uname -m) for non-x86_64 support in build.sh

---

build/doc.sh
build/quick_ref.py

Several of the tests continue to refer to /usr/bin/python. I don't
know of a way to fix these, as they call python -S and IIRC shebangs
can only include one parameter…

Make more shebangs compatible

---

bin/oil.py

support running as -osh for use as login shell

---

spec/show-fd-table.sh
spec/var-sub-quote.test.sh
test/spec-runner.sh
test/spec.sh

Hope you don't mind me lumping this all up in one PR, if that's a problem I can split it.
This improves portability to the point that the tests will run on NixOS; there's still a multitude of failures caused by the assumption that ls lives in /bin, but it's a start :)

Tests: portability improvements and additional test

---

core/builtin.py

`pushd` and `popd` were crashing when given malformed input or absent input. I've added some error handling to prevent those crashes. The error messages are the same as given by `pushd` and `popd` in bash.

Adds error handling to the `pushd` and `popd` builtins.

---

core/builtin.py

This pull request contains the code for the `dirs` builtin flags: -v, -p, and -c. The `bash` implementation also has the -l flag, but that has not yet been written.

Implement `dirs` builtin flags

---

.travis.yml

There seems to be nice test coverage so it would be a good idea to run those tests on all new code submissions.  This configuration will enable Travis CI to run [flake8](http://flake8.pycqa.org) tests on all pull requests before they are reviewed. We could also run the /test directory tests.  This allows contributors and maintainers to make sure no errors are introduced before new code is reviewed.  The owner of this repo would need to go to https://travis-ci.org/profile (log in via GitHub id) and flip the repository switch __on__ to enable free, automated testing of each pull request.

Let's run tests on all new code submissions

---

.travis.yml
README.md

Spent a shameful amount of time trying to see why it didn't build the shell.
(Please consider I hadn't worked with Travis before)
About VM's vs containers... I don't know if you explicitly prefer one over
the other. I chose to approach the problem using containers since they boot
considerably faster than VMs. If you'd rather use VMs, just
substitute the `addons.apt.packages` and `before_install` lines for:
```yml
sudo: required
before_install:
- build/dev.sh ubuntu-deps
```
Again, the advantage I see of containers over VMs is that they boot faster. The
disadvantage is that now dependecies must be stated in `build/dev.sh` AND
`.travis.yml`.
I'll look into making the tarball and binary builds.
Any guidance is well-received.

Make travis perform developer build, run {unit,spec} tests.

---

spec/redirect.test.sh
test/spec.sh

Just adding a spec test for stdout/stderr output redirection appending to a target (file, stream, device, etc). It's basically a copy pasta of the regular spec test for `&>` except that it puts some data into the target file before trying to append (so that it's evident that the subsequent operation appends to the file instead of overwriting it)

Adds spec test for stdout and stderr redirection appending to a target.

---

osh/word_parse.py

I was expecting the fix to require additional changes further up the call stack, but apparently most of the error handling was already in place and only this one function didn't have the necessary check.

Handle parsing failure in _ReadVarOpArg (#100)

---

core/builtin.py
spec/builtins.test.sh
test/spec.sh

Fixes #86 (at least for `cd`, which is the example given in the description).
Currently the only supported arguments are `-L` and `-P`. These are the only arguments required for POSIX compliance, but others do exist (e.g. my version of Bash has `-e` and, of all things, `-@`).
Adds three spec tests for checking how `cd` interacts with symlinks. The new spec tests all pass.
I do not know if `args.py` supports a way to ensure that "mode" arguments can be overridden. In this case, `cd -P -L` should behave like `cd -L`, but I don't know how to implement that.

Implement cd -P and -L; respect --

---

core/builtin.py
core/cmd_exec.py
core/runtime.asdl
opy/_regtest/src/_devbuild/gen/runtime_asdl.py
spec/builtins.test.sh

A simple `pwd` builtin that emulates the other common shells by making `-L` the default (rather than `-P`, the default in the GNU coreutils binary).
Fixes #110.

Implement the pwd builtin

---

core/cmd_exec.py
spec/for-expr.test.sh

Before this change
```bash
bin/osh -c 'for ((;;)) do done'
```
crashes with
```python
...
File "core/cmd_exec.py", line 1000, in _Dispatch
self.arith_ev.Eval(node.init)
File "core/expr_eval.py", line 252, in Eval
if node.tag == arith_expr_e.ArithVarRef:  # $(( x ))
AttributeError: 'NoneType' object has no attribute 'tag'
```
because there is no initializer expression.
Additionally (but unrelated to this bug), I'm not sure whether `do done` should be a valid loop body. `bash` doesn't accept it.

Fix crash on empty for expression ((;;))

---

spec/append.test.sh
spec/builtin-io.test.sh
spec/command-sub.test.sh
spec/var-op-strip.test.sh
spec/var-sub-quote.test.sh

Maybe my dev environment just isn't set up correctly, but `argv` alone doesn't work for me. Since some of the other spec tests use `argv.py` as well, I assume that's the correct command.

Use argv.py instead of argv in spec tests

---

core/expr_eval.py
core/state.py
core/state_test.py
core/word_eval.py
spec/array.test.sh

Actually this PR doesn't fix a lot yet, even when the correct number of `None`s is appended, a lot of code in other places blows up when it receives a `None` instead of the expected string.
I'm not even sure whether `None` is the right default to use here, since in the case below where the array *doesn't* exist, you use `''` instead. Have you gotten a better understanding since you wrote that TODO comment?

Handle arrays with partially unset elements

---

native/libc.c
native/libc_test.py

This diff adds simple support for BASH_REMATCH environment variable that exports a regex's capture groups

implement BASH_REMATCH (#133)

---

core/word_eval.py
spec/var-op-other.test.sh

The length operator ${#s} returns the number of code points now instead
of the number of bytes. Also added a test for this. Addresses #142.

Fix unicode string length

---

asdl/pretty.py
build/codegen.sh
build/dev.sh
core/glob_.py
core/glob_test.py
core/libstr.py
osh/cmd_parse.py
osh/glob.asdl
osh/meta.py

Zulip thread: https://oilshell.zulipchat.com/#narrow/stream/121540-oil-discuss
Github issue: https://github.com/oilshell/oil/issues/125

parse glob to AST

---

spec/builtins.test.sh
test/sh_spec.py

Missed the comments, so this just fixes that error.

Update code comments to match new spec format

---

test/sh_spec.py

There are some small mistakes in some of the comments that have
been overlooked from the commit that reformatted the spec tests.
This commit amends those errors for consistent documentation.

Fix comment errors

---

core/builtin.py
core/cmd_exec.py
spec/compgen.test.sh
test/spec.sh

This merge adds `compgen -A function` to osh. Not sure if `compgen` should be in `cmd_exec.py` or `builtins` so the previous is commented out.

Add compgen function to osh

---

spec/builtins.test.sh

This leaves `git status` clean after `test/spec.sh all`.

[spec/builtins] Tuck a couple of stray directories under tmpdir.

---

core/word_eval.py
spec/var-ref.test.sh
test/spec.sh

This is enough to make bash-completion begin to work! Seems to have a bit of debug/warning spew, but the functionality is there now, for filename completion and for compopt. After
```
$ bin/osh
osh$ . ~/src/bash-completion/bash_completion
```
I can complete `ls bui` to the filename `build`:
```
osh$ ls bui-vprintf: warning: ignoring excess arguments, starting with ‘quoted’
ld
```
and `diff --` with the many options to `diff`:
```
osh$ diff --compopt ['-o', 'nospace']
compopt ['-o', 'nospace']
--GTYPE-group-format=       --ignore-file-name-case     --report-identical-files
--LTYPE-line-format=        --ignore-matching-lines=    --show-c-function
--brief                     --ignore-space-change       --show-function-line=
[... lots more ...]
```

Implement ${!ref} when $ref is like arr[1].

---

core/builtin.py
core/cmd_exec.py
core/runtime.asdl
spec/builtin-printf.test.sh
test/spec.sh

Passes one spec test!
And good enough to run bash_completion, and now without the message
-vprintf: warning: ignoring excess arguments, starting with ‘quoted’
we were seeing, which is from /usr/bin/printf not understanding `-v`.
This shadows /usr/bin/printf, which has more functionality but also
differs from the shell builtin.  So some scripts that worked may now
fail, in which case the fix is to add the missing functionality here.
Fixes an item in #208.

Crude first version of printf builtin

---

README.md

scripts/count.sh was moved to metrics/source-code.sh previously in
commit ce71e0c3d216a4963a41f04de31b18e0be76500f
(also this project is seriously cool. :)

[cleanup] Fix location of script in README.md

---

core/process.py

closes https://github.com/oilshell/oil/issues/258
this turned out to be simpler than I expected, since posix has a way to get how a process exited from its status.

print newline after process is interrupted

---

build/compile.sh

Hi! I was trying to compile on Mac OS X with readline and ran into some small trouble with
build/compile.sh. Making this change solved it. I haven't tested this on linux as the change is rather trivial, but I can if that would be helpful.
Summary:
If $READLINE_DIR is specified, $readline_flags becomes something like:
`"-L /usr/local/opt/readline/lib -I /usr/local/opt/readline/include-l readline -D HAVE_READLINE"`
And the lack of space between the include and the `-l` trips up clang on mac.
Changes:
This commit adds an extra space to separate the `-I` and `-l` flags to `cc`.
Test plan:
Was able to build osh on Mac OS X with
`./configure --prefix ~ --with-readline --readline /usr/local/opt/readline`
where I was not previously.

build/compile.sh: fix bug in $READLINE_DIR flags

---

build/dev.sh

* Print usage when no arguments are passed to the `build/dev.sh` script.
Signed-off-by: mr.Shu <mr@shu.io>

build/dev.sh: When no arguments, print usage

---

osh/word_eval.py

* Do not import the `sys` module in `word_eval.py` as it is not used
there.
* Fix TravisCI build as a result.
Signed-off-by: mr.Shu <mr@shu.io>

fix: TravisCI linter by not importing unused sys

---

osh/expr_eval.py

* Implement the `-o` option for the test command (`[[ -o val ]]`).
* Fix  #338
Signed-off-by: mr.Shu <mr@shu.io>

expr_eval: Implement `[[ -o val ]]` option

---

osh/cmd_exec.py
spec/builtin-eval-source.test.sh
spec/posix.test.sh

Gives precendence to $PATH before sourcing files in current directory
TIL: sourcing files in the current directory is a bash-ism, not part of POSIX,
see http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#dot
Addresses https://github.com/oilshell/oil/issues/389

Lookup files to be sourced in $PATH

---

core/property_tests.py
vendor/typing.py

As discussed in https://github.com/oilshell/oil/issues/394. Adds a dependency on [`hypothesis`](https://hypothesis.readthedocs.io/en/latest/quickstart.html#running-tests) for tests.
Note that the tests will fail until https://github.com/oilshell/oil/pull/402 is merged.

Add property testing using hypothesis

---

test/lint.sh

I have `flake8` installed on my machine, but it's the python3 version, which throws a bunch of bogus errors for python2 code. This uses the python2 version regardless of the one in `$PATH`.

Use python2 version of flake8

---

native/libc.c

Before:
```
osh$ [[ 1 =~ [0-9] ]]
Segmentation fault (core dumped)
```
After:
```
osh$ [[ 1 =~ [0-9] ]]
osh$ echo $?
0
```
This happened because libc.c used the GNU regex library headers but
used the BSD library when dynamically linked. I'm not sure why it was
using different headers, maybe Python was originally statically linked?

Don't crash when parsing regexes on FreeBSD

---

doc/README.md
doc/osh.1

Following mdoc/man documentation ( [intro/synopsis_util](http://mandoc.bsd.lv/mdoc/intro/synopsis_util.html), [man(7)](http://mandoc.bsd.lv/man/mdoc.7.html) )
TODO: Update info from other pieces of existing Osh documentation

Update man page to use (semantic) mdoc macros

---

core/main_loop.py
spec/interactive.test.sh
test/sh_spec.py

Location information is wrong - PROMPT_COMMAND=';' gives a traceback
pointing to ~/.local/oil/oshrc instead of [ interactive ] or
[ PROMPT_COMMAND ]
Other than that, this seems to be working pretty well with my patched version of bash-git-prompt.
Addresses https://github.com/oilshell/oil/issues/400

Take a stab at PROMPT_COMMAND

---

test/spec-bin.sh

Instead of typing 5 similar commands in a row, let the shell do it for me.

[devtools] Add make-all helper function to spec-bin.sh

---

demo/read-n-demo.sh
osh/builtin.py
spec/builtins2.test.sh

Puts TTY into 'noncanonical' mode for duration of read
Calls posix.read n times, since each time will only return 1 byte
Restore original mode even if an exception occurs
Addresses https://github.com/oilshell/oil/issues/274

Read in unbuffered mode for `read -n`

---

native/libc.c
osh/string_ops.py
osh/string_ops_test.py
spec/var-op-strip.test.sh
test/spec.sh

Fixes: #173 
Hi @andychu, this one turned out to be a bit tricker than I thought.  I needed to change func_fnmatch in libc.c to set the locale to "" (making it refer to the environment variables) -- otherwise it assumed LANG=C, which meant that fnmatch did not properly handle multibyte characters.  I'm not sure if this was the best way to deal with this.
Also, it turns out that iterating backwards over a UTF-8 string is not substantially harder than going forwards, so I did that, rather than iterating forwards and building up a list of indexes as was suggested by your comment above DoUnarySuffixOp.
I hope this is alright.  I spent more time checking edge cases so as not to embarrass myself again :)

Fix handling of unicode in affix removal (${s#?} and ${s%?})

---

native/libc.c
test/spec.sh

Using the environment's locale instead of the default "C" locale
allows regcomp to understand UTF-8.
(finally got around to this tiny fix...)

[test/spec] fix var-op-patsub "Substitute one unicode character" test

---

devtools/make_help.py

The error is:
File "devtools/make_help.py", line 706, in <module>
main(sys.argv)
File "devtools/make_help.py", line 577, in main
d = pprint.pformat(topic_lookup)
UnboundLocalError: local variable 'pprint' referenced before assignment

[fix] extra import of pprint in devtools/make_help.py can cause error

---

osh/bool_parse.py
osh/builtin_bracket.py
osh/expr_eval.py
osh/word_compile.py
types/common.sh
types/more-oil-manifest.txt
types/osh-parse.sh
types/run.sh

Also:
* create a manifest for typecheck-more-oil files instead of specifying all the filenames inline.
* make typecheck-more-oil stop returning errors for dependencies of specified modules, using the `--follow-imports=silent` option to mypy.

Add annotations and enable typechecking for osh/word_compile.py and osh/builtin_bracket.py

---

frontend/syntax_abbrev.py

This was a bit confusing to me at first.

[doc] clarify docstring of frontend/syntax_abbrev.py

---

osh/state_test.py

This makes the test pass on my system (Arch linux).  I tried not to weaken the test too much.

[fix] fix osh/state_test.py incorrectly assuming where env binary will *not* be

---

oil_lang/regex_translate.py
types/more-oil-manifest.txt

oil_lang/regex_translate.py needed substantial annotation changes, while core/main_loop.py was already passing mypy.

Add typechecking for 2 more files

---

devtools/findclassdefs.py
devtools/typeimports.py
types/run.sh

These are very hacky and intended to be temporary, just until the type annotation is completed.
@andychu I'm working on adding type annotations to osh/word_eval.py, and I decided that I've been spending too much time manually updating imports, so I wrote these helpers.  I don't know if anyone else will want to use them, but I thought it was better to commit them than not.

[types] add scripts/function to help maintain correct imports when adding type annotation

---

tools/deps.py

I'm not sure this is the "right" fix, but after introspecting for a while I did find a fix that solves the AttributeError and does appear returns the right list of attributes here:
```
...
self.VisitChildren(node)
File "/Users/abathur/work/oil/tools/deps.py", line 32, in VisitChildren
for name, _ in node.ASDL_TYPE.GetFields():
AttributeError: 'NoneType' object has no attribute 'GetFields'
```

fix NoneType attribute error

---

core/completion_test.py

This is per the tests in #612, but the issue sounds like it's cut a little more broadly, so I won't assert that this fixes it.

skip compl. tests that fail on darwin/macOS

---

spec/errexit-oil.test.sh

This spec fails on nixos. After grepping around, I think it's also the last remaining spec that tries to *run* a hardcoded executable path. The logs attached below show verbose output for just this spec before and after the change:
[fail before nixos](https://github.com/oilshell/oil/files/4303585/errexit_nixos_local_fail.txt)
[pass after nixos](https://github.com/oilshell/oil/files/4303586/errexit_nixos_local_pass.txt)
For reference, here are clean before/afters of the same job for linux and macOS:
[pass before linux](https://travis-ci.org/abathur/oil/jobs/659853026#L3274)
[pass before macos](https://travis-ci.org/abathur/oil/jobs/659853027#L3346)
[pass after linux](https://travis-ci.org/abathur/oil/jobs/659859815#L3274)
[pass after …

fix absolute executable path in errexit-oil spec

---

spec/builtin-completion.test.sh

I see consistent breaks here on nixos due to a different sort order of the file entries at the end. In response, I borrowed the PA/_Q pattern you used for functions. I didn't want to pipe the output through sort, because the existing test also covers the behavior of generating results in argument order.
[fail before nixos](https://github.com/oilshell/oil/files/4303758/compgen_before_nixos_fail.txt)
[pass after nixos](https://github.com/oilshell/oil/files/4303759/compgen_after_nixos_pass.txt)
I'm not exactly sure what's going on here, but I've fiddled with this a little and it looks like I see a different, stable, unsorted order on each problem. It smells like different random seeds. (I also statted the files on macos and see that they aren't sorted by inode, and all have the same …

fix flaky file completion order in builtin-completion

---

spec/builtin-dirs.test.sh

Both cases try to use /lib, which neither macos nor nixos have. Instead of
making a longer, more abstract fix, I'm just swapping this for /dev. I checked
several docsets and didn't see a *nix without it, so it should at least be
"more" portable.
[fail before nixos](https://github.com/oilshell/oil/files/4303992/nixos_before_fail.txt)
[fail before macos](https://travis-ci.org/abathur/oil/jobs/659895964#L3349) (forgot to run case 6 here, but it fails the same way)
[pass after nixos](https://github.com/oilshell/oil/files/4303993/nixos_after_pass.txt)
[pass after macos](https://travis-ci.org/abathur/oil/jobs/659922765#L3346)
And, as before:
[pass before linux](https://travis-ci.org/abathur/oil/jobs/659895963#L3274) (forgot to run case 6 here, but it also passes)
[pass after …

[spec/builtin-dirs] swap /lib for more-portable /dev

---

osh/word_eval.py
spec/introspect.test.sh
spec/testdata/bash-source-string.sh
spec/testdata/bash-source-string2.sh

Related to the second point in https://github.com/oilshell/oil/issues/653#issuecomment-599087679. I found that `BASH_SOURCE` is specially treated (de92fc57). `BASH_LINENO` and `FUNCNAME` are also members of the same family. They are original scalar variables and later extended to an array variable. They should allow both form of `$X` and `${X[0]}`.
Note: When I create a test, I noticed that there is a difference between Bash and Oil for `FUNCNAME` in source contexts, i.e., `FUNCNAME=` in Bash and `FUNCNAME=source` in Oil. The added test is created for the Oil behavior.

Allow scalar form of BASH_LINENO and FUNCNAME

---

osh/word_eval.py
spec/var-op-bash.test.sh

See the fourth item in https://github.com/oilshell/oil/issues/653#issuecomment-599087679.
> See the following test case. Even though it succeeds for the first time, it fails for the second time.
> 
> **test3.sh**
> ```bash
> #!/usr/bin/env bash
> 
> abc_hello=1
> function hello1 { echo "${!abc_@}"; }
> hello1
> hello1
> ```
> 
> ```console
> $ osh test3.sh
> abc_hello
>   function hello1 { echo "${!abc_@}"; }
>                              ^~~~
> test3.sh:4: fatal: Bad indirect expansion: ''
> ```

[word_eval] Fix the ${!prefix@} failure for the second time

---

osh/word_eval.py
spec/word-split.test.sh

This is a quick fix for the third item in https://github.com/oilshell/oil/issues/653#issuecomment-599087679. I tried to make the change small, so it might not be so elegant.
Note: `dash` and `mksh` fail in `test/spec.sh word-split` for newly added tests because they don't support `${@:offset:length}`.

[word_eval] Fix shifted slicing of ${@:offset:length}.

---

frontend/id_kind_def.py
frontend/lexer_def.py
frontend/syntax.asdl
osh/builtin_printf.py
spec/builtin-printf.test.sh

Resolve #650
- 44d5af8e: Support `%()T`
- 8142a783: Support `%6.s` (fix parsing of precision)
- 99ead0e7: Support `%*.*s`
- c5d87362: Update test case for `#` flag
In the implementation of `%()T`, I needed to reflect the exported shell variable `TZ` in the real environment variable `TZ`. [This](https://github.com/oilshell/oil/blob/44d5af8e/osh/builtin_printf.py#L261-L268) is the corresponding section. I'm not sure whether I did this in the right way. (Maybe a new method like `self.mem.GetExportedVar(name)` should be added to `class Mem`). Could you check and edit if necessary?
In the current master branch, the parsing of `%6.s` is broken to generate the following errors (`s` is treated as a precision), so I added a check for the precision and treat missing precision as `0` (as POSIX …

Implement printf %()T %.s %*s %.*s

---

spec/arith.test.sh
test/spec.sh

Add tests to demonstrate a use case of dynamical rvalue/lvalue variable names in arithmetic expressions.

[test/spec] Failing spec tests for rvalue dynamic var name in arith

---

core/state.py
osh/builtin_assign.py
osh/string_ops.py
spec/assign-extended.test.sh

Support `declare` and `declare -p` (cf #647, but `declare -f`, `trap`, `trap -p` are not yet supported)
- Note: Bash quotes the values with double quotations, but this patch uses single quotations provided by `string_opt.ShellQuote`.
- Note: Bash ignores the flag `-g` when `-p` flag is specified, but this patch supports it.
- Note: Bash ignores the flags `-nrxaA` when `-p` flag and variable names are specified, but this patch supports them.
- Please see the changes in `spec/assign-extended.test.sh` for the detailed behavior

[builtin/declare] Support -p

---

bin/oil.py
core/process.py
core/process_test.py
frontend/consts.py
frontend/lexer_def.py
frontend/syntax.asdl
osh/cmd_exec.py
osh/cmd_parse.py
osh/runtime.asdl
spec/redirect.test.sh
test/spec.sh

The arguments don't match with the function declaration? I guess the test is old. If this is not the right fix, please let me know.
This demonstrates bugs related to the subsequent fixes (4., 5., and 6.) and also includes tests for `20> file` and a Bash bug.
This is a bug fix. The file descriptor was broken with `echo 3>&3`. The following test case (in `spec/redirect.test.sh`) had been failing due to this bug.
```bash
: 3>&3
echo hello
```
This is another fix. The order of restoring original fds in `saved` and `need_close` were mixed. The ordering should be preserved. The following test case (in `spec/redirect.test.sh`) had failed due to this problem:
```bash
exec 3> "$TMP/fd.txt"
echo hello 3>&- << EOF
EOF
echo world >&3
exec 3>&-
cat "$TMP/fd.txt"
hello
world
```
See the following test …

[core/process] Fix/Implement redirections <>, 5>&-, 6>&5-, {fd}>file, etc.

---

spec/ble-idioms.test.sh
test/spec.sh

`spec/ble-idioms.test.sh` mentioned in https://github.com/oilshell/oil/issues/653#issuecomment-605771723.

[test/spec] Failing spec tests for recursive arithmetic evaluations

---

osh/sh_expr_eval.py
spec/arith.test.sh

This fixes the problem that `echo $((10#0123))` outputs `3210`.
```bash
$ osh -c 'echo $((10#0123))'
3210
```

[arith] Fix reversed digits in $((base#num)).

---

core/process.py
spec/redirect.test.sh

- 77e3af8 Add failing test cases which are fixed by the subsequent fixes.
- abe89a5 Fix *"#653 33. BUG: Redirection of 2 is persistent after `: 2>/dev/null >&30`"*
- 4ed53e1 Fix *"#653 37. BUG: `{fd}>&-` does not close the fd"*
- 7f86a1a Fix a problem that `>&100` does not fail even if fd 100 does not exist.

[core/process] Fix redirections

---

osh/word_eval.py
spec/introspect.test.sh

This fixes the following issues:
- The parameter expansions of the form `${#BASH_SOURCE}` for array variables counts the number of elements instead of the number of characters of the first element.
```bash
$ osh -c 'f1() { echo ${#BASH_SOURCE}; }; f1'
1
```
- Slices of the parameter expansions `${BASH_SOURCE:offset:length}` are used to select array elements
```bash
$ osh -c 'f1() { echo ${BASH_SOURCE::1}; }; f1'
-c flag
$ osh -c 'f1() { echo ${BASH_SOURCE:1}; }; f1'
```
- `set -u` doesn't detect undefined first elements with the scalar form `$BASH_SOURCE`.
```bash
$ osh -uc 'echo ${BASH_SOURCE[0]}'
echo ${BASH_SOURCE[0]}
^~~~
[ -c flag ]:1: fatal: Undefined variable
$ osh -uc 'echo $BASH_SOURCE'
```

[word_eval] Fix ${#BASH_SOURCE}, ${BASH_SOURCE:offset:length}, etc.

---

osh/builtin_misc.py
spec/builtin-io.test.sh

This fixes the problem that when `read -n` is used with tempenv, the resulting variable is created in the tempenv frame so that one cannot access the results:
```bash
$ bash -c 'v= read -n 1 <<< X; echo "[$REPLY]"'
[X]
$ osh -c 'v= read -n 1 <<< X; echo "[$REPLY]"'
[]
```

[builtin/read] Fix 'IFS= read -n' bug.

---

osh/builtin_printf.py
spec/builtin-printf.test.sh

`ble.sh` needs this to read <kbd>NUL</kbd> (which is the terminal sequence of <Kbd>C-@</kbd>) for emulated `read`.

[builtin/printf] Support printf %d \'.

---

osh/builtin_assign.py
spec/assign.test.sh

When `declare -a array` is performed on existing arrays, the array becomes empty. In this PR, the arrays are initialized only when the variable contains another type of value. This also fixes the same problem for associative arrays.
```bash
$ bash -c 'var=hello; declare -r var; declare -p var'
declare -r var="hello"
$ osh -c 'var=hello; declare -r var; declare -p var'
declare -r var=hello
$ bash -c 'arr=(1 2 3); declare -a arr; declare -p arr'
declare -a arr=([0]="1" [1]="2" [2]="3")
$ osh -c 'arr=(1 2 3); declare -a arr; declare -p arr'
declare -a arr=()
```

[builtin/assign] Do not remove existing arrays by 'declare -a array'.

---

osh/sh_expr_eval.py
osh/word_eval.py
spec/ble-features.test.sh
spec/introspect.test.sh

Ref #726 
- Fix a problem that the scalar form cannot be used in arithmetic expressions (9fc20e7f Test c2365f5f Fix):
```bash
$ osh -c '$((BASH_LINENO))'
$((BASH_LINENO))
^~~~~~~~~~~
[ -c flag ]:1: fatal: Expected a value convertible to integer, got value.MaybeStrArray
```
- Implement `shopt -s compat_array` to allow `$array` (Test bf9f3328, Fix 67047709)
- Disallow `${#BASH_SOURCE}`, `${BASH_SOURCE:1:1}`, `${BASH_SOURCE#X}`, `${BASH_SOURCE-X}`, etc. by default (Fix b1a16c25). In this implementation, everything with additional suffix/prefix are disallowed.

[word_eval] Implement 'shopt -s compat_array'.

---

doc/idioms.md

running the idiom with the not_mutated example will currently yield a failure
```
echo $not_mutated
^~~~~~~~~~~~
./backup.sh:5: fatal: Undefined variable 'not_mutated'
```
It seems to me that the examples should run as is.
Let me know if you need anything else.

idiom: fix run failures

---

doc/framing.md
doc/idioms.md
doc/options.md

As discussed, some simple fixes to remove this common typo, based on a simple grep search.

Remove instances of "the the" from documentation.

---

osh/builtin_meta.py
spec/builtin-eval-source.test.sh
spec/redirect.test.sh
test/spec.sh

Most shells don't appear to complain about sourcing a directory, but bash does and it certainly seems like it should be an error. Regardless, this ensures that the whole shell doesn't exit in this case. This solves #1043 .
It was unclear to me where to look for the code for redirection that seems to have the same problem so I didn't attempt to fix that, but I did add a failing spec test for that mentioned in #1044 .

Handle error when sourcing a directory

---

frontend/flag_def.py
spec/sh-usage.test.sh

Bash supports these flags to indicate that it should run as a login shell. This adds these flags as a no-op to osh since osh doesn't currently behave differently as a login vs. non-login shell.
Please let me know if this is the wrong place/way to test or fix this.
Fixes #1052

Add -l and --login flags as no-op

---

core/error.py
doc/osh-help-topics.md
frontend/option_def.py
osh/cmd_eval.py
osh/glob_.py
spec/glob.test.sh
test/spec.sh

This implements failglob for osh. I'm not sure about the error message setup here, it could be too verbose, but bash prints a message for this in addition to setting a non-zero status. Also could be missing some contexts, but this appears to do the right thing for command context, loop context, and array literals.
In reference to #1036

Implement failglob

---

core/completion.py

While trying to figure out why [aliases and functions were not getting
suggested by the completion system](https://github.com/oilshell/oil/issues/1064), I noticed a small typo in a comment, that prevented it from showing up when I searched for appearances of `compgen` in the repository.

Fix minor typo in core/completion.py

---

frontend/lexer_def.py

While building with build/dev.sh all, re2c complained about null bytes. After checking [the re2c manual](https://re2c.org/manual/warnings/warnings.html#wsentinel-in-midrule), i added \0 to the excluded bytes.
> _devbuild/tmp/osh-lex.re2c.h:652:37: error: sentinel symbol 0 occurs in the middle of the rule (note: if a different sentinel symbol is used, specify it with 're2c:sentinel' configuration) [-Werror-sentinel-in-midrule]
> _devbuild/tmp/osh-lex.re2c.h:720:37: error: sentinel symbol 0 occurs in the middle of the rule (note: if a different sentinel symbol is used, specify it with 're2c:sentinel' configuration) [-Werror-sentinel-in-midrule]
> _devbuild/tmp/osh-lex.re2c.h:886:37: error: sentinel symbol 0 occurs in the middle of the rule (note: if a different sentinel symbol is used, …

Disallow null bytes inside of re2c rules.

---

.gitpod.yml
README.md

Howdy,
Geoff here from Gitpod. Stumbled upon this conversation over at https://lobste.rs/s/s5co2f/where_contributors_have_problems_with related to problems that contributors to Oil are facing and this pull-request contains the required configuration that enables folks to one-click / start contributing to Oil immediately from any device. 
You can even try it out on this pull-request before merging by clicking on the button below :)
<a href="https://gitpod.io/#https://github.com/oilshell/oil/pull/1156">
</a>
If you got any questions lemme know.
pps. nix-shell is installed on Gitpod but I didn't go that route because saw conversation that the paths had diverged.

Enable software development from any device via https://gitpod.io

---

Python-2.7.13/Python/_warnings.c

macOS release build of oil-0.10.1 throws an error on the `make` step.
This is with oil-0.10.1.tar.gz from the website; have not checked if the
brew version suffers from the same issue.
After running `make`, from Python-2.7.13/Python/_warnings.c:
> implicitly declaring library function 'tolower' with type 'int (int)'
with a helpful note to:
> include the header <ctype.h> or explicitly provide a declaration for 'tolower'
This appears to be the same error mentioned in https://github.com/oilshell/oil/issues/978 in the
“So I attempted to install from source” section.
There’s a bunch of warnings too and then at the strip substep there’s a
final error because:
> can't open file: _build/oil/ovm-opt (No such file or directory)
After nuking everything I included <ctype.h> then started the build …

[build] Fix broken macOS build from source

---

test/spec-cpp.sh

Previously, running `test/spec-cpp.sh run-with-osh-eval smoke` would
fail with:
IOError: [Errno 2] No such file or directory: '_tmp/spec/cpp/smoke.tsv'
Now it succeeds.

Ensure that the spec test tsv output directory exists

---

osh/cmd_parse.py
test/baseline.spec-cpp.assertion_fails
test/baseline.spec-cpp.results

Long story short, we've got to initialize these with an empty array or
the code that executes for loops tries to dereference 0 and crashes.

Init BraceGroup() with empty array

---

cpp/leaky_posix.h

Previously this was throwing IOError (by value) for which there is no matching handler.
Now it throws OSError* to match its python equivalent (and exception handler in the translated code that calls it).
With this change there's no delta cpp for command_ spec tests!

Throw OSError* from posix::execve() to match python

---

cpp/leaky_stdlib.h
spec/bugs.test.sh

Calls in python to posix._exit() were being translated into calls to
exit(), which has different semantics. Now it calls _exit() as expected.
Testing:
```bash
> cat >/tmp/f.sh <<'EOF'
echo start
$(:)
echo end
EOF
> _bin/cxx-dbg/osh_eval /tmp/f.sh
start
end
end
> _bin/cxx-dbg/osh_eval /tmp/f.sh
start
end
```
@andychu Sorry if this is mentioned somewhere and I missed it. Will the CI automatically flag any regressions caused by a change like this? I'm not sure if I should be running something locally to verify or not

[cpp] posix::_exit() now calls _exit(), not exit() (#1233)

---

core/shell_native.py
osh/builtin_process.py
osh/builtin_process2.py

I started translating `wait` and found that it was pretty much already translatable! 
I moved `class Wait` but I had to make one minor modification to it (GH is not smart enough to show the diff as a move + a  change).  I'll comment on the diff to point it out
Makes osh_eval native pass 14/16 of the background spec tests. Up from 0/16.

Translate the wait builtin

---

mycpp/gc_mylib.h
mycpp/leaky_builtins.cc
mycpp/leaky_mylib.cc
mycpp/leaky_mylib.h

The former will be a GC-managed object used by generated code.
The latter is a global, and can be a local in fmt123() functions.
This was a smell -- the APIs were almost totally disjoint!
class BufWriter : public Writer
getvalue()
write()
...
class FormatStringer
getvalue()
reset()        // could go away
write_const()
format_r()
format_s()
format_d()
...

[mycpp/runtime] Separate BufWriter and FormatStringer

---

cpp/leaky_libc.cc
cpp/leaky_stdlib.h

I had to make this change to get the oil-native build working with gcc 10.X

[cpp] add misisng errno include

---

cpp/leaky_stdlib.cc
cpp/leaky_stdlib.h
mycpp/leaky_mylib.cc
osh/builtin_process2.py

These should fix two failures found by `./test/spec-cpp.sh run-with-osh-eval builtins` (`get umask` and `set umask in octal`)
@andychu any reason we had `int umask(int)` instead of `mode_t umask(mode_t)`? The commit that tweaks that isn't essential, but I figured it was worth updating while I was in that region

[cpp] some umask fixes

---

core/state.py

Doesn't look like we know how to translate list comprehensions yet. Turning the ones in the accessors for `_pipeline_status` and `_process_sub_status` into vanilla loops brings us up to parity with `osh.py` for `spec/pipeline` and `spec/process-sub`

[core] imperative-ize a few list comprehensions

---

cpp/leaky_core.cc

Should fix `spec-cpp/builtin-times`

[cpp/core] add missing newline to `times` output

---

core/process.py
core/pyos.py
cpp/leaky_core.cc
cpp/leaky_core.h

This commit adds a wrapper around `signal.signal()` called `Sigaction()` and adds a C++ implementation for basic signal dispositions like SIG_DFL and SIG_IGN. We can use this to share some post-fork signal setup between python and C++.
A future commit will also use this to make some other signal-related code translatable.

[core] make post-fork signal setup translatable

---

core/pyos.py
core/shell.py
core/shell_native.py
core/test_lib.py
cpp/leaky_core.h
osh/builtin_trap.py
osh/cmd_eval.py

This is the first commit in a series that will refactor the signal and trap handling code to make it safely shareable between ptyhon and C++.
The first step in this process is to remove the illusion that the various users of the trap-related state each own it. We can make it more obvious that they're really borrowing global state by renaming the member(s) they all use to access it.

[core] move trap-related state into SignalState

---

core/process.py
core/process_test.py
core/pyos.py
core/shell.py
core/shell_native.py
core/test_lib.py
cpp/leaky_core.cc
cpp/leaky_core.h
osh/builtin_trap.py
osh/cmd_eval.py

This is the second-to-last PR in the signal series. It's size is primarily because of the cut-and-paste of `SignalState` from `pyos` into `builtin_trap`. Otherwise it's mostly some house-keeping. After this the API between the main loop and pyos/kernel is just the six small functions below. The rest of the signal handling code is shared with the hook handling code in the main loop and is all translatable python. I think I like this API, but I'm open to comments, e.g. `SetSigwinchCode()` is a little awkward, but I think it's the least awkward option.
```
def Sigaction(sig_num, handler):
"""Set the disposition of a signal. handler is either SIG_DFL or SIG_IGN"""
def RegisterSignalInterest(sig_num):
"""Have the kernel notify the main loop about the given signal"""
def GetPendingSignals(): …
```

[core,osh] make SignalState translatable

---

mycpp/cppgen_pass.py

This fixes the generated code to catch `std::exception`, as well as anything that inherits from it, rather than just `std::exception`. See `-Wcatch-value` documentation for details.

fix `-Wcatch-value` in gen code

---

frontend/consts_gen.py

We currently use the `StrFromC(char *)` form for `Str` creation in the generated character lookup tables for C++. This means '\0' gets interpreted as the empty string instead of a string of length one with a NULL byte in it.  Using the `StrFromC(char *, int)` form fixes this. For characters other than '\0' this should make no difference.

[frontend] make str lens explicit in lookup tables

---

spec/oil-builtin-argparse.test.sh

I finally found some time to do something about the spec tests for argparse.
Now I'm really unsure if it more or less resembles what we discussed, I think some of your points went over my head plus I read through the python argparse manual and took a lot of inspiration. The idea is that the hay definition should feel as much as possible like the python argparse definitions.
I intentionally only implemented 2 spec tests because I'm very unsure if they make sense! I'll add more spec tests for different features once these are approved 🙂 
I will do a final rebase (with proper commit naming) lateron

Create two basic spectests for argparse

---

cpp/README.md
cpp/qsn.h
cpp/qsn_test.cc
mycpp/gc_str.h

Remove the old rooting style.
Also update cpp/README.md with the new structure.

[cpp/qsn] Optimize rooting for core/qsn functions

---

doc/eggex.md

The previous formatting and examples could mislead one to think that `%start %end` is an example, using dummy names, for a type of expression that has an opening and a closing marker (and possibly some content within).
By splitting the code markup, adding a comma, and using a second example that isn't complementary to the first one, the actual syntax is made clearer.

eggex.md: clarify zero-width assertions

---

mycpp/gc_builtins.cc
mycpp/gc_builtins.h
mycpp/gc_str.cc
mycpp/gc_str.h
mycpp/gc_str_test.cc
mycpp/mark_sweep_heap.cc

This will make it easier to support dynamic format strigns when translating modules like core/comp_ui. It will also allow us to skip gnerating format string functions in mycpp, which should lead to smaller binaries (and less bespoke code to scan when debugging).
This commit just adds a library. A follow-up will update mycpp to generate code that uses it.

[mycpp] add StrFormat()

---

benchmarks/gc.sh
benchmarks/parse-help.sh
benchmarks/parse-help/clang.txt
benchmarks/report.R

There are 5 workloads, compared with 2 builds of OSH, 5 possible runtime options, and bash/dash/zsh.
Doesn't take too long to execute!
- Add Clang data file for bashcomp-parse-help

[benchmarks/gc] Add more workloads, including shell execution.

---

build/dynamic-deps.sh
core/comp_ui.py
core/comp_ui_test.py
core/shell_native.py
cpp/core.h
cpp/libc.cc
cpp/libc.h
mycpp/gc_builtins.cc
mycpp/gc_builtins.h
mycpp/gc_builtins_test.cc
mycpp/gc_list.h
prebuilt/dynamic-deps/filter-translate.txt

Everything but the readline and completion dependencies can be translated now. Let's fold them into `shell_native.py`.
This PR also includes some commits that add C++ versions of the builtins needed by `comp_ui`.

[core] make comp_ui translatable

---

mycpp/cppgen_pass.py
mycpp/examples/iterators.py
mycpp/gc_builtins.h
mycpp/gc_list.h

This commit is a first attempt at translating generator functions. If mycpp sees a function that returns `typing.Iterator[T]` it will generate a C++ function with a type signature that differs in the following ways:
1) it returns `void` instead of `Iterator[T]`
2) it has an extra ouput param of type `List<T>*`
The defintion of the function emitted by mycpp will be identical to its pythonic ancestor, except all `yield ...` statements will be translated into calls to `append(...)` on the output param from (2).
At the call sites for the function mycpp will allocate a temporary `List<T>` on the stack and pass it as an ouput param to the modified function as an accumulator the generator's output, which will be computed in one big batch. All subsequent statements that refer to the generator …

[mycpp] emit code for generators

---

core/completion.py
mycpp/examples/iterators.py
mycpp/gc_list.h
mycpp/gc_list_test.cc

This is the last non-mechanical thing we need to figure out before completion can be made translatable.

[translation] make iterator state in ReadlineCallback translatable

---

core/main_loop.py

Another case of `break`ing inside of a type switch inside of a loop causing chaos

[core] refactor main loop to avoid ambiguous break

---

cpp/frontend_pyreadline.cc

Else we end up with awkward spaces after <TAB>-completion.

[cpp] set rl_completion_append_character to NUL

---

core/executor.py
core/ui.py
osh/cmd_eval.py
soil/worker.sh

The same can be done for Print_() and PrintMessage(), which now take a span_id, but should take a location.

[refactor] Type-driven refactoring: remove span_id in PrefixPrint()

---

cpp/frontend_pyreadline.cc
frontend/reader.py

This removes the stutter that happens from readline redisplaying to
stdout when osh-cpp is running with -i as part of a pipeline.
This should fix `spec/interactive`

[cpp] don't use readline if stdio is not tty

---

soil/worker.sh

This should fix the 'spec-cpp' delta in the CI to match what devtools/release.sh reports.

[soil] Run build/py.sh all in cpp-spec task

---

spec/redirect.test.sh
test/spec.sh

Add a spec test for this bash only behaviour. From the man page:
```
There are two formats for redirecting standard output and standard error:
&>word
and
>&word
```
Should osh be matching this behaviour do you think? It's in ubuntu's default bashrc (which is how I came across this):
```
λ grep '>&' /etc/skel/.bashrc
if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
```

[spec/redirect] Add a test for bash's handling of >&file

---

test/spec.sh

Make test/spec.sh slightly friendlier/discoverable by listing available functions/subcommands when invoked with -h/--help or no args.
This uses a simplistic method to list the functions which has problems (main is listed, for example) but it's a good start and goes most of the way to making it more usable for new contributors.
Here's the output (with a wide terminal):
```
λ test/spec.sh --help
Usage: test/spec.sh <function> [<args>]
For bash completion of available functions, run:
source devtools/completion.bash
For more help try passing --help, e.g.,
test/spec.sh alias --help
Available functions:
TODO-deprecate                  builtin-vars                    loop                            oil-options                     sh-spec-smoosh-env
_list-funcs                     builtins …
```

Add usage info to test/spec.sh

---

benchmarks/compute.sh
core/pyos.py
cpp/core.h
cpp/core_test.cc
cpp/data_race_test.cc
osh/builtin_trap.py

- AFTER: http://travis-ci.oilshell.org/github-jobs/2023-02-19__21-36-31.wwz/_tmp/gc/index.html
- max RSS MB of compute-fib and parse-abuild-help is 8.0 and 9.0 MB
- allocated MB is 35.0 and 49.2
- BEFORE: http://travis-ci.oilshell.org/github-jobs/2023-02-19__21-18-05.wwz/_tmp/gc/index.html
- max RSS MB is 11.2 and 12.5 MB
- allocated MB is 166.0 and 162.0

[core optimize] SignalSafe::ReuseEmptyList() avoids many allocations

---

.clang-format
test/lint.sh

This makes it easier to use clang-format in other ways (e.g., `git clang-format`) or via an editor.

Move clang-format config to .clang-format

---

spec/append.test.sh
spec/bugs.test.sh
spec/if_.test.sh

I noticed that there are some non-metadata comments starting with `##` when writing my own parser of Oil's spec tests [1]. There are just a few of them, so I assume the use of `##` is accidental; changing them to `#` makes the spec files just a little bit easier to parse.
There is another place that is slightly weird (not changed in this PR):
https://github.com/oilshell/oil/blob/ed3f591537ffd754dc5770a8ad310544147cd683/spec/arith.test.sh#L362
This is the only metadata line that starts directly with a shell name, without `OK` / `BUG` / `N-I`. Reading the comment for this test case, 9 is the expected output on all shells, so presumably the `osh` part can just be removed?
[1] It's in https://github.com/elves/posixsh/blob/master/pkg/spec/oil_specs_test.go if you're interested; the project …

spec: Don't use ## for non-metadata comments.

---

core/optview_gen.py
cpp/core.h
cpp/frontend_flag_spec.h
cpp/frontend_match.h
cpp/frontend_pyreadline.h
cpp/pgen2.h
frontend/flag_gen.py
mycpp/cppgen_pass.py
mycpp/gc_builtins.h
mycpp/gc_dict.h
mycpp/gc_list.h
mycpp/gc_obj.h
mycpp/gc_tuple.h
mycpp/mark_sweep_heap_test.cc
prebuilt/asdl/runtime.mycpp.h
prebuilt/core/error.mycpp.h
prebuilt/frontend/args.mycpp.cc
prebuilt/frontend/args.mycpp.h

In various places (mainly the field_mask() functions) we previously represented field masks with uint16_t's even though the ObjHeader allocates 24 bits for them. Now we use uint32_t instead.
I'm motivated to do this now because my upcoming change to move the object header outside of objects results in one type requiring 17 bits for its field mask (the field masks get one bit longer).
Note: The only manual change here was increasing `kFieldMaskBits` to 24. The rest is: `s/uint16_t field_mask/uint32_t field_mask/`

[cpp] Use uint32_t to represent field masks

---

mycpp/gc_obj.h

These were obsoleted by #1517 (d383581cc11b9d34284816aa2d23c5bc36f53c1b) but I forgot to delete them!

[cpp] Delete unused GC_* macros

---

.git-blame-ignore-revs

And initialize it with a python code formatting change.
To configure git locally:
git config blame.ignoreRevsFile .git-blame-ignore-revs
For more info see:
https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

Add a .git-blame-ignore-revs

---

mycpp/mark_sweep_heap.cc
mycpp/mark_sweep_heap.h

Previously MarkSweepHeap's live_objs_ and to_free_ were vectors of RawObject*, but now they contain ObjHeader* instead. It's slightly less code this way.

[cpp] MarkSweepHeap stores lists of ObjHeader*

---

cpp/osh.cc
mycpp/demo/gc_header.cc
mycpp/gc_list.h
mycpp/gc_list_test.cc
mycpp/gc_obj.h
mycpp/gc_str.h

is_header no longer used so remove it. We now have a spare bit!

[cpp] Remove ObjHeader::is_header

---

benchmarks/time-helper.c

I debugged this issue while trying to run the benchmarks and noticing they were silently failing! 
time-helper was hitting this "unreachable" abort() on my system because getopt() returns an int but we were assigning it to a char. This breaks when 'char' is 'unsigned char' (because getopt() can return -1).

[benchmarks] Fix time-helper bug

---

build/deps.sh

PY3_BUILD_DEPS wasn't being expanded as an array.

[build/deps] Fix bug where PY3_BUILD_DEPS are not installed

---

build/ninja-rules-cpp.sh

Just wanted this while doing something else.
Tested by running both:
```
TIME_TSV_OUT=/tmp/t OIL_NINJA_VERBOSE=1 ninja
OIL_NINJA_VERBOSE=1 ninja
```
and verifying the command line output and timing output file look as expected

[build] Make the link step respect OIL_NINJA_VERBOSE

---

core/executor.py

[core] Don't call setpgid() for command subs

---

core/shell.py
core/test_lib.py
frontend/flag_def.py
osh/builtin_lib.py
osh/builtin_lib_test.py
spec/builtins2.test.sh

Now we can do something like this:
```sh
$ echo 'start of osh session'
start of osh session
$ cat ~/.config/oil/history_osh
$ history -a
$ cat ~/.config/oil/history_osh
echo 'start of osh session'
cat ~/.config/oil/history_osh
history -a
```

[builtin/history] Add support for '-a' (append) flag

---

core/shell.py
core/test_lib.py
osh/builtin_lib.py
osh/builtin_lib_test.py
spec/builtin-history.test.sh
spec/builtins2.test.sh
test/spec.sh
test/spec_osh.py

As per https://github.com/oilshell/oil/pull/1587#discussion_r1181092501.
---
While working on this I realized we were missing the case where `HISTFILE` does not point to a file (even if it's a valid string). This should return an error code if a user tries to then `history -r`.

[test/spec] Split history builtin tests from builtins2 tests

---

frontend/syntax.asdl
osh/cmd_eval.py
osh/cmd_parse.py

Nodes changed:
- `command.AndOr`
- `command.ShAssignment`
- `command.Pipeline`
- `command.Case`

[osh refactor] Replace spids with explicit token fields

---

test/ble.sh

The current version 0.15.0 of osh can parse all the modules used in the full tests of ble.sh (with adjustments in branch `osh` of ble.sh), so we can now run the full tests.

[soil/app-tests] Run the full tests of ble.sh

---

core/runtime.asdl
frontend/syntax.asdl
mycpp/cppgen_pass.py
mycpp/examples/containers.py
mycpp/examples/strings.py
mycpp/gc_list.h
mycpp/gc_list_test.cc
mycpp/gc_str.cc
mycpp/gc_str.h
oil_lang/expr_eval.py
oil_lang/expr_to_ast.py
spec/oil-slice-range.test.sh
test/oil-runtime-errors.sh
test/parse-errors.sh

This patch adds ranges, slices, and tuples to the runtime and 
statically types the expression evaluators for slices, ranges, tuples,
lists, dictionaries, and if-statements. 
It also adds limited stride support to slices and updates a few spec
tests to reflect the latest dictionary semantics, namely: only strings
can be used as keys now (tuples, ints, etc... have been dropped).

[oil_lang] statically type some more expression evaluators

---

frontend/parse_lib.py
osh/cmd_parse.py
osh/cmd_parse_test.py
osh/word_parse.py
test/parse-errors.sh
ysh/expr_to_ast.py
ysh/grammar.pgen2
ysh/grammar_gen.py

Ie. this can now be parsed:
```
case (x) {
(1) | (2) {
echo number
}
}
```

[ysh language] Parse multiple expression case patterns

---

build/ninja-rules-cpp.sh
configure
configure-test.sh
cpp/core.cc

This includes a change to check for `unistd.h` defining `environ` and one for the correct `ld` flags to use. This has currently only been tested on macos, so confirmation that this doesn't break linux would be welcome.
This should fix #1658 and at least the `environ` part of #1272.

Compatibility changes for building oil-native on macos

---

osh/cmd_eval.py
osh/word_eval.py
spec/ysh-with-sh.test.sh
test/lint.sh

- No longer allowed on any YSH types, e.g. Int
- This is issue #840
- Rewrite using 'with tagswitch'
And
- Revert List/Dict change for ${#x}. This is polluated by the ${#x[0]} issue

[osh-language] Tighten up behavior of x+=1 on different types

---

core/runtime.asdl
library/func_cpython.py
spec/ysh-slice-range.test.sh
ysh/cpython.py
ysh/expr_eval.py

With this change slices can only be created with the `:` syntax.

[ysh] remove slice(), drop step from value.Slice

---

uninstall

The ysh symlink is not being removed by the uninstall script. Add it to the FOR loop along with "osh" and "oil", so there's no leftovers.
That second change at the end of the file was added by Neovim:
``` diff
❯ git diff master origin/fix/add-missing-ysh-to-uninstall
diff --git a/uninstall b/uninstall
index 06b0aaca3..3377c6646 100755
--- a/uninstall
+++ b/uninstall
@@ -37,7 +37,7 @@ main() {
local working_dir=$PWD  # save for later
cd "$bin_dest"
-  for link in osh oil; do
+  for link in osh oil ysh; do
if ! rm "$bin_dest/$link"; then
log "Couldn't remove $link symlink in $bin_dest"
else
@@ -65,4 +65,4 @@ main() {
fi
}
-main "$@"
\ No newline at end of file
+main "$@"
```

Add missing ysh to uninstall script

---

core/executor.py
core/main_loop.py
core/process.py
core/pyos.py
core/shell.py
cpp/core.cc
cpp/core.h
cpp/core_test.cc
osh/builtin_process.py
spec/stateful/interactive.py
spec/stateful/job_control.py
spec/ysh-xtrace.test.sh
test/stateful.sh

[core] print notifications when bg jobs complete
To support notifying users about the completion of background jobs, this
commit updates the main loop for the interactive shell to pass the
WNOHANG to `WaitPid()`, adds state to `Job` about background/foreground
positioning. It also removes the `WhenDone()` method from `JobList` to
make reading the job completion codepath easier.
[core] only take back tty on stop if necessary
When the main shell wakes up from wait() with WIFSTOPPED, it
unconditionally takes back the TTY from whichever process was just
stopped. This can cause problems when running background jobs, though.
Consider the following script:
$ cat &
$ cat
The first cat is forked and placed into its own process group. The shell
remains in the foreground. This means cat will …

job control overhaul

---

core/process.py
osh/builtin_process.py
spec/background.test.sh

Right now this table grows unbounded.
This commit also removes the log generated by `wait` when a job doesn't exist. This isn't a fundamental thing, but it keeps the spec tests "clean". Happy to roll that change back if you think the log will be helpful, @andychu.

[core] clean up child process state on exit

---

.github/FUNDING.yml

If you merge this and enable "Sponsorships" in the repository settings, GitHub will display a sponsor button in the repository sidebar as follows:

[github] Add FUNDING.yml

---

frontend/syntax.asdl
library/func_cpython.py
osh/cmd_eval.py
spec/ysh-funcs-builtin.test.sh
spec/ysh-funcs.test.sh
spec/ysh-slice-range.test.sh
spec/ysh-word-eval.test.sh
test/spec.sh
ysh/cpython.py
ysh/expr_eval.py
ysh/expr_to_ast.py
ysh/val_ops.py

These commits replace the `range` builtin with `:` syntax for range creation. You can now do loops like the following:
```
$ bin/ysh
ysh$ for i in (0:10) { echo "$[i]" }
0
1
2
3
4
5
6
7
8
9
ysh$
```
In the current implementation, ranges must have both limits specified. So, ranges like `:10` that are otherwise equivalent to the one in the example, are disallowed. How do we feel about this?

[ysh] remove range() builtin, add RangeIterator

---

core/shell.py
core/state.py
library/func_cpython.py
library/func_misc.py
osh/cmd_eval.py
spec/ysh-expr.test.sh
spec/ysh-funcs-builtin.test.sh
spec/ysh-user-feedback.test.sh

This patch implements `len()` over `value_t`. It also fixes some error presentation code in the command evaluator

[ysh] implement len() as vm.Callable

---

frontend/typed_args.py
frontend/typed_args_test.py
library/func_hay.py
library/func_misc.py
ysh/val_ops.py

This patch implements the positional and named arg parts. I left out the stuff for procs for now, since I haven't been following the discussions around what we need there.
I added some unit tests to serve as documentation of sorts. Let me know if you think we should add more comprehensive ones though.

[frontend] Fill Out typed_args::Reader

---

osh/builtin_meta.py

This reduces the delta cpp by 2.

[translation] Fix crash in oils-native from misuse of `error`

---

devtools/release.sh
doc/ref/chap-builtin-func.md
doc/ref/toc-ysh.md

I don't like that I have to write "Note, you will need to `source --builtin <some-file>.ysh` to use this function" everywhere. Maybe we can add a link to the right of the function name? We might be able to fit a link to the source location there too.
But, this should be fine on it's own. I can always do the above changes in another PR.
EDIT: Here's the rendered docs for reference http://travis-ci.oilshell.org/github-jobs/4914/ovm-tarball.wwz/_release/VERSION/doc/ref/chap-builtin-func.html#abs.

[docs] Document all stdlib/{math,list}.ysh functions

---

frontend/typed_args.py
osh/builtin_meta.py
spec/ysh-builtin-error.test.sh
ysh/expr_eval.py

This will cause error messages+codes to change for the error builtin, but now they are closer to what we have for the other builtin functions.
In order to make this work, we have to evaluate all arguments before constructing the `typed_args.Reader`. So previously something like `error (not_an_arg=42/0)` would fail on the `not_an_arg`, but now it fails on `42/0`. I think this may actually be a good thing as it better matches other languages such as python:
```py
>>> def myfunc(named_arg=2):
...   return named_arg
... 
>>> myfunc(different_arg=42/0)
File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
>>> myfunc(different_arg=42)
File "<stdin>", line 1, in <module>
TypeError: myfunc() got an unexpected …
```

[builtin/error] Update the error builtin to use typed_args.Reader

---

core/shell.py
frontend/lexer_def.py
frontend/syntax.asdl
frontend/typed_args.py
library/func_misc.py
spec/ysh-expr.test.sh
ysh/expr_eval.py
ysh/expr_to_ast.py
ysh/grammar.pgen2

Adds support for expression literals:
```
ysh$ var l = ^[1 + 2]
ysh$ = type(l)
(Str)   'Expr'
ysh$ = evalExpr(l)
(Int)   3
```

[ysh] Expression Literals

---

build/ninja-rules-py.sh
mycpp/cppgen_pass.py
mycpp/mycpp_main.py
soil/worker.sh

Output on master.
```
WARNING: RootCompleter::Matches() has 29 stack roots. Consider refactoring this function.
WARNING: ::_PrintVariables() has 25 stack roots. Consider refactoring this function.
WARNING: SpecBuilder::Build() has 18 stack roots. Consider refactoring this function.
WARNING: Printf::_Format() has 23 stack roots. Consider refactoring this function.
WARNING: Printf::Run() has 17 stack roots. Consider refactoring this function.
WARNING: CommandEvaluator::_Dispatch() has 39 stack roots. Consider refactoring this function.
WARNING: ::_MakeAssignPair() has 19 stack roots. Consider refactoring this function.
WARNING: CommandParser::_MaybeExpandAliases() has 17 stack roots. Consider refactoring this function.
WARNING: CommandParser::ParseSimpleCommand() has 18 stack roots. …
```

[mycpp] warn about excessive stack roots

---

osh/cmd_eval.py
spec/ysh-expr-compare.test.sh
test/parse-errors.sh
test/ysh-runtime-errors.sh
ysh/expr_eval.py
ysh/val_ops.py

Issue: #1732
Now we raise a `error.TypeErr` when comparing non-comparable types.
```sh
ysh$ = {}->keys === {}->keys
= {}->keys === {}->keys
^
[ interactive ]:1: fatal: Cannot compare this type, got BuiltinMethod
```

[ysh] Fix Crash When Comparing Non-Comparable Types

---

spec/glob.test.sh
spec/globignore.test.sh
test/spec.sh

Partially addresses #609
Cases generally use `echo *.*` because spec test setup create a subdirectory _tmp. That gets included when using `echo *` and would prove brittle if the test setup changes. The single character range case is a little awkward because it first removes the auto-generated _tmp dir.

[test/spec] Spec tests for GLOBIGNORE

---

builtin/method_dict.py
core/shell.py
doc/ref/chap-type-method.md
spec/ysh-methods.test.sh

C++ probably fails because I don't wrap the elements in a `value.X` but we'll see :)

[builtins/dict] add => values() method

---

spec/builtins2.test.sh

Test of `command -p` that ignores existing PATH in favor of a default system PATH
Currently, dash/bash/mksh/zsh pass, osh fails.
Adds tests for, but does not fix, #1795

Add spec test for command with -p flag

---

doc/eggex.md
spec/ysh-regex-api.test.sh

The [current docs](https://www.oilshell.org/release/0.19.0/doc/eggex.html#flags-and-translation-preferences) do not cover any of the [currently implemented eggex flags](https://github.com/oilshell/oil/blob/139146035a4f76a9fbaf88eb9ee61e3759c84be5/ysh/regex_translate.py#L371). I have added documentation for those flags:
- `i`/`reg_icase` [REG_ICASE](https://www.gnu.org/software/libc/manual/html_node/Flags-for-POSIX-Regexps.html)
- `reg_newline` [REG_NEWLINE](https://www.gnu.org/software/libc/manual/html_node/Flags-for-POSIX-Regexps.html)
There were no tests for `reg_newline`, so I added some in `spec/ysh-reggex-api`.

Document Eggex Flags

---

cpp/frontend_flag_spec.cc
cpp/frontend_flag_spec.h
frontend/flag_spec.py

We don't have a faithful translation of both ParseLikeEcho() and ParseCmdval().
Refactor to use default argument value.

[translation] Make note of different with frontend/flag_spec

---

builtin/pure_ysh.py
core/shell.py
core/state.py
devtools/format.sh
doc/ref/chap-builtin-cmd.md
doc/ref/toc-ysh.md
frontend/builtin_def.py
frontend/flag_def.py
spec/ysh-builtin-ctx.test.sh
test/spec.sh

This is a rough draft of the `ctx` builtin. It has implemented these verbs:
- `push`
- `set`
- `emit`
Here's an example which will now run:
```
var p = {}
ctx push (p) {
ctx set (help="This is a help message")
ctx emit flags ({short_name: '-v'})
ctx emit flags ({short_name: '-h'})
}
```

Prototype the ctx builtin

---

builtin/pure_ysh.py
spec/ysh-stdlib-args.test.sh
stdlib/args.ysh

- In the `ctx` builtin change `error.FatalRuntime(3, ...)` to `error.Expr(...)`
- Use the `ctx` builtin for the arg-spec construction API

Use the new ctx builtin in parseArgs()

---

builtin/assign_osh.py
builtin/completion_osh.py
builtin/completion_ysh.py
builtin/dirs_osh.py
builtin/error_ysh.py
builtin/io_osh.py
builtin/io_ysh.py
builtin/json_ysh.py
builtin/meta_osh.py
builtin/misc_osh.py
builtin/module_ysh.py
builtin/printf_osh.py
builtin/process_osh.py
builtin/pure_osh.py
builtin/pure_ysh.py
builtin/read_osh.py
builtin/readline_osh.py
builtin/trap_osh.py
core/shell.py
cpp/frontend_flag_spec.cc
cpp/frontend_flag_spec.h
cpp/frontend_flag_spec_test.cc
frontend/flag_spec.py
frontend/flag_util.py
pea/oils-typecheck.txt

Move it to frontend/flag_util.py.
This fixes a couple bugs in test/spec-cpp.sh runfile builtin-io.  And it reduces the amount of hand-written C++!

[translation fix] Auto-translate more of frontend/flag_spec.py

---

core/executor.py
doc/error-catalog.md
test/runtime-errors.sh

I came across this while working on `args.ysh` and got this confusing error message when I forgot to `source --builtin args.ysh`:
```
arg-parse (&spec) {
^
[ stdin ]:1: fatal: Unexpected typed args passed to external command 'arg-parse'
```

Add OILS-ERR-200 - Unexpected typed args passed to an external command

---

doc/ref/chap-builtin-cmd.md
doc/ref/toc-ysh.md
spec/ysh-stdlib-args.test.sh
stdlib/args.ysh

I started adding support for `default` in `parseArgs`, but then got carried away :P
- Set `default` values for flags and args in `parseArgs`
- Add `doc/ref` entries for `Args Parser`, `parser`, `flag`, `arg`, `rest` and `parseArgs()`
- Enforce required positional arguments
- Move default and help into named arguments for `flag` and `arg`
- Raise an error on duplicate flag/arg names

Misc. Argparse Updates

---

doc/error-catalog.md
doc/ref/chap-expr-lang.md
test/runtime-errors.sh
ysh/expr_eval.py

From zulip: [#language-design > Awk has annoying string <-> int conversion](https://oilshell.zulipchat.com/#narrow/stream/384942-language-design/topic/Awk.20has.20annoying.20string.20.3C-.3E.20int.20conversion).
> ```
> ysh ysh-0.21.0$ = '100' + '10a'
>   = '100' + '10a'
>           ^
> [ interactive ]:6: fatal: Binary operator expected numbers, got Str and Str
> ```
> 
> Maybe worth an entry in the error catalogue? `+` technically works on number formatted strings, we should note that.

[docs/error-catalogue] Add OILS-ERR-201, Str with arithmetic operators

---

build/deps.sh

As title. Closes https://github.com/oilshell/oil/issues/1927

$PY_FTP_MIRROR allowing user to override mirror for python FTP site. 

---

.envrc

Ready for merge.
Direnv is a tool for user to separate their shell config into different folder specific profile. When `cd`ing into the `oil` folder, if direnv is allowed to run the script, it will automatically run the `build/dev-shell.sh` script. and dump environment variables into current shell.
- [Install direnv and its shell hook](https://direnv.net/#getting-started)
- cd into git repo root
- Run `direnv allow`
- Now whenever you cd into oil repo or one of its subdirs, direnv will load environment variables directly for you.

direnv support

---

core/process.py

I only half-way fixed #1003 in 12697216532eea6b04c98a5f59015372b8efd27a. We should remove all processes from the child process map on exit, not just the ones that have been backgrounded and assigned job IDs.

always clean up child process on exit

---

spec/ysh-methods.test.sh

I had this in my work tree before starting a fix for the J8 UTF-8 bug. It can be merged on it's own if you want.

Add failing test case for correctness errors in osh/string_ops utf8 decoders

---

spec/builtin-completion.test.sh

As discussed on [Zulip](https://oilshell.zulipchat.com/#narrow/stream/146045-shell-autocompletion/topic/Bash.20completion.20compatibility.20status.3F), this adds spec tests for `compgen -k` and `compgen -e`. bash passes all tests, and osh does not.
In particular, `compgen -e` might be easy to implement, since it's very similar to `compgen -v`, which is already done. The difference is `-e` completes exported vars, and `-v` completes _all_ vars.
`compgen -k` returns/completes shell reserved keywords.

Add compgen -k and -e spec tests

---

data_lang/NINJA_subgraph.py
data_lang/j8.h
data_lang/utf8.h
data_lang/utf8_test.cc
spec/ysh-json.test.sh

I ended up writing a new UTF-8 decoder from scratch. It follows the Crockford style but 1) is stateless and 2) can round-trip surrogates. I've also written some fairly comprehensive tests for the decoder.
Now the `J8EncodeOne` function is able round-trip surrogates!

[data_lang/utf8] Create UTF8 decoder to round-trip surrogates. Fix J8 lone surrogate spec test

---

build/deps.sh
build/detect-systemtap-sdt.c
configure
configure-test.sh
core/main_loop.py
core/process.py
deps/from-apt.sh
mycpp/const_pass.py
mycpp/cppgen_pass.py
mycpp/mylib.py
mycpp/probes.h
mycpp/runtime.h
osh/cmd_eval.py

This commit adds some infrastructure for adding static tracepoints to the shell runtime and a few examples of how to use it.
These trace points can be used with tools like linux perf/ebpf and dtrace to give us a better idea about what the shell is doing at runtime.
These should impose no overhead when compiled in unless they are being actively instrumented with a tool. See the output below for two of the workloads tracked by CI. Each were measured ten times and all starts are reported with their standard deviations.
```
$ perf stat -r 10 -o perf-output.txt taskset -a -c 2 /home/melvin/workdir/oil/_bin/cxx-opt/osh /home/melvin/workdir/oil/testdata/osh-runtime/bin_true.sh 1000                                                                          [136/137]
Performance counter stats for …
```

add some statically defined tracepoints

---

doc/hay.md

This commit updates the the link from the former, unofficial nixos wiki page to the new https://wiki.nixos.org
ref: NixOS/foundation#113

link to official nixos wiki

---

cpp/data_lang.cc
cpp/data_lang_test.cc
data_lang/utf8.h
data_lang/utf8_test.cc
osh/string_ops.py
pyext/fastfunc.c
pyext/fastfunc_test.py
spec/ysh-methods.test.sh

Per the discussion in #1965, I've made the following updates:
- Made the `fastfunc.Utf8DecodeOne` "safe" by exposing the python2/oils string model (over the C one)
- Removed the NUL special casing in our `osh/string_ops.py` UTF-8 functions (`fastfunc.Utf8DecodeOne` now handles that)
- Added some tests to validate that string APIs like `Str => trim*()` are resilient to zero-codepoints

[fastfunc] Use the python2/oils string model in Utf8DecodeOne

---

mycpp/pass_state.py
mycpp/pass_state_test.py

This commit adds a library for implementing a simple control flow graph. Right now it doesn't have any meaningful statement annotations, nor is it connected to anything in mycpp. Future commits will build on top of this to generate datalog programs to perform analyses like the call-graph analysis from #1963 or the alias or stack root analysis from #1972.

mycpp: add ControlFlowGraph library

---

mycpp/cppgen_pass.py
mycpp/pass_state.py
mycpp/pass_state_test.py
mycpp/util.py

Subclass names can collide, e.g. `builtin.func_misc.Type` and `builtin.meta_osh.Type` which share the base `core.vm._Callable`. This isn't a big deal until you need to query the subclass->base relationship, which a future commit will do.
This commit also changes `pass_state.Virtual.virtuals` into a mapping from (class, method) -> (base, method). If an entry maps to `None` that means the given method is part of the base class. This will allow a future commit to find the base for a given subclass.
The commit also changes mycpp to use fully-qualified class names when interacting with `pass_state.Virtual` to avoid ambiguity.

mycpp: avoid subclass name colissions

---

doc/j8-notation.md

Use `#` instead of `//` in the examples to match the description

FIX: comments in j8 examples should use # instead of //

---

spec/var-sub.test.sh
test/sh_spec.py

Without the fix, the following fails with:
```
ysh-builtin-shopt: FATAL: Got 2 failures (1 oils failures), but 1 are allowed
```
With the fix, it is fine, as both osh python and osh native works the same.
```
$ test/spec-cpp.sh run-file ysh-builtin-shopt
ysh-builtin-shopt.test.sh
case    line    osh     osh-cpp
0       3     pass    pass    shopt supports long flags
1      17     pass    pass    shopt supports 'set' options
2      30     pass    pass    shopt --unset errexit { }
3      51     pass    pass    shopt -p works correctly inside block
4      65     pass    pass    shopt --set GROUP { }
5     111     pass    pass    shopt and block status
6     124     pass    pass    shopt usage error
7     137     pass    pass    shopt -p
8     162     FAIL    FAIL    TODO: all options as a …
```

Fixes spec cpp counts

---

mycpp/cppgen_pass.py
mycpp/ir_pass.py
mycpp/pass_state.py
mycpp/util.py
mycpp/visitor.py

The `SimpleVisitor` base class was missing these before. This was causing `ir_pass` to run into various collisions that `cppgen_pass` wasn't. Fixing this allows us to make `HeapObjectMember` more strict, which simplifies the next datalog patch.

[mycpp] share if-statement special cases with all visitors

---

mycpp/gc_list.h
mycpp/gc_list_test.cc

Fix for `List::Pop(int i)` for any non-zero positive `i`.
Found in #2028.

[WIP] Fix mycpp List::Pop(int)

---

data_lang/pretty.asdl
data_lang/pretty.py
data_lang/pretty_test.txt

Fix a bug in pretty printing tabular alignment (it must force elements to be flat).
The new test case is robust against differing values of `_DEFAULT_MAX_TABULAR_WIDTH`.

Fix pp tabular

---

builtin/method_dict.py
core/shell.py
doc/ref/chap-type-method.md
mycpp/cppgen_pass.py
spec/ysh-methods.test.sh

An oddity is that `erase` works with both `->` and `=>` despite only mutating, not transforming. But this behaviour matches other Dict and List methods, so the implementations are at least consistent with each other.

[builtins/dict] add -> erase() method

---

builtin/method_dict.py
core/shell.py
doc/ref/chap-type-method.md
spec/ysh-methods.test.sh

Use verbose variable name `default_value` because `default` breaks mycpp, which seems to confuse it for the default case in a switch statement. (Going by an initial read of the errors. I haven't dug into it.)
This implementation makes the default value a required argument, but I can make it optional (more Pythonic) if preferred.
Still a bit confused about `=>` vs `->` because all `Dict` methods, including this one, seem to work with both.

[builtins] Add Dict => get() method

---

builtin/method_str.py
builtin/pure_ysh.py
core/state.py
spec/ysh-builtin-eval.test.sh

This test captures the effect of this change:
```
proc local-scope {
var myVar = "foo"
eval (^(echo $myVar), vars={ someOtherVar: "bar" })
eval (^(echo $myVar))
}
var myVar = "baz"
eval (^(echo $myVar), vars={ someOtherVar: "bar" })
eval (^(echo $myVar))
local-scope
baz
baz
foo
foo
```

Don't push a new frame in `eval ()`

---

spec/arith-dynamic.test.sh
test/spec.sh

These cases were extracted from the discussion on Zulip
(#oil-dev>ArithSub evaluation bug in autotools configure)

Add failing arith-dynamic spec tests

---

builtin/method_str.py
doc/ref/chap-type-method.md
spec/ysh-regex-api.test.sh

This PR fixes the following issues:
- Infinite loop if we have a zero-width match
- Crash if the string contains a NUL byte

Fix issues in `Str => replace(eggex, *)`

---

build/ninja_main.py

The header of this shell script states that the compiler can be either `cxx` or `clang` (but it can be anything) and it states that the default `VARIANT` is `'dbg'`, which is [disproved few lines below](https://github.com/oils-for-unix/oils/blob/master/build/ninja_main.py#L133):
```sh
local variant=${2:-opt}    # default is optimized build
```

Correct misleading comment in `_build/oils.sh`

---

benchmarks/autoconf.sh
benchmarks/common.sh
benchmarks/compute.sh
benchmarks/gc.sh
benchmarks/id.sh
benchmarks/osh-parser.sh
benchmarks/osh-runtime.sh
benchmarks/report.R
benchmarks/report_test.R
bin/NINJA_subgraph.py
build/native.sh
build/ninja-rules-py.sh
build/ninja_lib.py
build/ninja_main.py
devtools/release-native.sh
devtools/test-oils.sh
mycpp/NINJA_subgraph.py
mycpp/mycpp_main.py
mycpp/pass_state.py
soil/cpp-tarball.sh
yaks/NINJA_subgraph.py

This commit adds a new translator called `mycpp-souffle`. It translates
files using mycpp with optimizations enabled.
You can build the translation examples with souffle optimizations
enabled with the same targets you normally would, but with `mycpp`
replaced by `mycpp-souffle` in the suffix. For example, you build the
intermediate C++ and the `cxx-asan` binary for
`mycpp/examples/gc_stack_roots.py` respectively by running the following
commands:
```
ninja _gen/mycpp/examples/gc_stack_roots.mycpp-souffle.cc
ninja _bin/cxx-asan/mycpp/examples/gc_stack_roots.mycpp-souffle
```
You can also build OSH and YSH with this new variant. Their targets are
named `_bin/<variant>/mycpp-souffle/osh` and
`_bin/<variant>/mycpp-soufle/ysh` respectively. Currently, only the
`cxx-opt`, `cxx-asan`, and …

add mycpp-souffle translator

---

core/state.py

Experiment for [#language-design>Metaprogramming in ysh, sort of](https://oilshell.zulipchat.com/#narrow/stream/384942-language-design/topic/Metaprogramming.20in.20ysh.2C.20sort.20of) on Zulip.

Define procs in the current scope, not the global one

---

doc/ref/chap-stdlib.md
stdlib/ysh/args-test.ysh
stdlib/ysh/args.ysh

Additionally, now that basic support for type objects has been added (ref: 9db992cc), refactor to use type objects for flag types. This provides a cleaner, more strict interface when describing flags (e.g., `flag -c --count (Int)`).

Extend args.ysh's flag proc with Float, Str support

---

doc/error-catalog.md
frontend/id_kind_def.py
frontend/lexer_def.py
test/ysh-parse-errors.sh
ysh/expr_parse.py

Lex '&&', '||' in expression mode for better error messages:
```
= a && b
^~
[ -c flag ]:1: Use 'and' in expression mode
= a || b
^~
[ -c flag ]:1: Use 'or' in expression mode
```
Eggex has `Expr_Bang` which means we cannot check this case the same way:
```
= !a
^
[ -c flag ]:1: Syntax error in expression (near Id.Expr_Bang)
```
(I don't think it's possible to cleanly check this specific error unless we moved away from pgen2.)

[ysh] Lex '&&', '||' for better errors in expr mode

---

stdlib/ysh/args-test.ysh
stdlib/ysh/args.ysh

Simplify and clarify the module interface by making the `flag`, `arg`, and `rest` procs private to the `parser` DSL.

In $LIB_YSH/args.ysh, make flag/arg/rest private to parser

---

doc/ref/chap-stdlib.md
stdlib/ysh/args-test.ysh
stdlib/ysh/args.ysh

Following the implementation of parameterized type objects in 4cbfa15f6, it is now possible to extend the set of supported flag types with List variants to provide multi-value flags.

[stdlib/args] Support flags that remember all values passed, with List[T] syntax

---

display/pp_value.py
spec/ysh-object.test.sh
spec/ysh-printing.test.sh

This commit adds a quick implementation of `pp value` (and by extension `=`) for objects. It generates pleasing output, but might not be optimal. I figure we can check this in and tweak it as we find cases that yield wonky outputs. What do folks think?

implement pretty printing for value.Obj

---

doc/getting-started.md

https://github.com/ajeetdsouza/zoxide#installation
As other similar adjustments may be required depending on the software one has installed under previous shell, it can be helpful to collect compatible configurations in a file under `/etc/profile.d` and source it from `oshrc` and keep shell-dependent ones such as `zoxide`’s in shell-specific files like `.bashrc` and `oshrc`.

Flag changes required by `zoxide` when sourcing other shell’s startup files

---

build/deps.sh

Small change in the dependency script to add Arch support. 
Also adds a check for whether or not you are in the right directory for running the file.

Add dependency installation script for arch

---

doc/error-catalog.md

Previously the OILS-ERR-10 entry would link to the wrong page.

Fix links from OILS-ERR-10 going to OSH cmd lang page not YSH cmd lang

---

NINJA-config.sh
build/dynamic-deps.sh

Fixes an issue discussed in [oil-dev > 2024-11-22 Meeting Zulip](https://oilshell.zulipchat.com/#narrow/channel/121539-oil-dev/topic/2024-11-22.20Meeting/near/484014206). The file `all-pairs.txt` generated by `build/dynamic_deps.py py-manifest` seems to contain the resolved path, while `REPO_ROOT` contained an unresolved path.

[build] Make NINJA-config.sh work in symlinked working directories

---

build/deps.sh

Without this package, `ninja` fails.

[build/deps] Add the "libasan" package to the Fedora dependencies

---

core/bash_impl.py
osh/word_eval.py
pea/oils-typecheck.txt

https://oilshell.zulipchat.com/#narrow/channel/121539-oil-dev/topic/2024-11-22.20Meeting/near/484115604
This creates a file `core/bash_impl.py` and includes the `Length` operation for BashArray/BashAssoc/SparseArray as an example.

[refactor] Add "core/bash_impl" for array operations

---

core/state.py
spec/array.test.sh

The current master crashes with the following:
```console
$ bin/osh -c 'arr=(); arr[-1]=1'
File "/home/murase/.mwg/git/oilshell/oil/bin/oils_for_unix.py", line 201, in <module>
File "/home/murase/.mwg/git/oilshell/oil/bin/oils_for_unix.py", line 170, in main
File "/home/murase/.mwg/git/oilshell/oil/bin/oils_for_unix.py", line 140, in AppBundleMain
File "/home/murase/.mwg/git/oilshell/oil/core/shell.py", line 1211, in Main
is_return, is_fatal = cmd_ev.ExecuteAndCatch(node, cmd_flags)
File …
```

[core/state] Fix BashArray crash on `a=(); a[-1]=1`

---

osh/sh_expr_eval.py
spec/array.test.sh

In the current master branch, `[[ -v a[-1] ]]` always returns exit status 1 even when there are elements and `"${a[-1]}"` is valid.

[osh/sh_expr_eval] Support `[[ -v a[-1] ]]` for BashArray

---

builtin/assign_osh.py
core/bash_impl.py
spec/ble-idioms.test.sh

This PR implements `declare -p sp` for SparseArray
In this PR, I currently use the form `([index]=value)` for `declare -p`, but this form was exclusively used for the associative arrays before, AFAICR. However, I also remember that we now have osh and ysh where osh is more compatible with Bash. What is the current situation for the representation of `([index]=value)`? Can I use this form for the sparse-array representation (assuming that it will be implemented in the future)?
Or do we need to stick with `(); name[index]=value; ...`? There are still other places that want to use the string representation of a sparse-array value, but the usage of the form `(); name[index]=value` is limited as the second part `; ...` is only valid as "a command".
Another related discussion would be the mixed …

[builtin/assign_osh] Support `declare -p` for SparseArray

---

builtin/assign_osh.py
core/bash_impl.py
core/dev.py
spec/assign-extended.test.sh

Note: This changes the result for an empty `BashAssoc`. We have been using `declare -A assoc` to mean an empty associative array while allowing `declare -A assoc=()` for *compatibility*. Now, this produces `declare -A assoc=()` for `declare -p assoc` to be consistent with Bash's output. **edit**: To explain the background, we want to call the ToStr function in [this form consistent with `BashArray`](https://github.com/oils-for-unix/oils/pull/2145/files#diff-828bd8642431550aea162b9540190291ce9f0cd52ce6b3c1041a09f585adbbe8R166), where the result is appended to `var_name=`. To append something to `declare -A assoc=` for an empty associative array, we need to use `()`.

[refactor] Add `Bash{Array,Assoc}_ToStrForShellPrint` for `declare -p` and `set -x`

---

builtin/assign_osh.py
core/bash_impl.py
core/state.py
osh/sh_expr_eval.py

https://github.com/oils-for-unix/oils/pull/2148#issuecomment-2508810745
This pull request also includes the fix of `tag in [...]` in previous PRs to `tag in (...)` (acde2712e47d09f0401b48d1150e484df31c5f1d).

[refactor] Format array-related codes with `yapf`

---

core/state.py
spec/array.test.sh

While Bash causes an error for `unset` with the invalid negative index,
```console
$ bash -c 'a=(1); unset -v "a[-2]"'
bash: line 1: unset: [-2]: bad array subscript
$ echo $?
1
```
the current `master` of `osh` succeeds silently:
```console
$ bin/osh -c 'a=(1); unset -v "a[-2]"'
$ echo $?
0
```
This patch adds the check and outputs an error message for the invalid negative index.

[core] Fix silent out-of-range error in unsetting BashArray element

---

mycpp/gc_mylib.cc

`mylib.BigIntSort()` is introduced to sort the keys of `SparseArray`. It was first introduced to implement the methods in `func_misc.SparseOp`.  It is related to `SparseArray` rather than `BashArray`.  This patch fixes the code comment for `BigIntSort`.

[mylib] Fix a code comment

---

core/state.py
spec/array.test.sh

This error message was introduced in #2137, but another error message introduced in the next https://github.com/oils-for-unix/oils/pull/2138#discussion_r1855493290 has been improved in https://github.com/oils-for-unix/oils/pull/2140#discussion_r1855505700.  This patch applies a similar improvement to the error message in #2137.

[core] Improve error message of out-of-bound index

---

bin/oils_for_unix.py

When we have multiple binaries of oil/osh/ysh of different versions, we want to call these binaries through the names `osh-0.23.0`, `osh-0.24.0`, etc.  However, with the current implementation of switching the mode by the basename of the command, one cannot use those versioned names to call oil/osh/ysh.  This PR loosens the condition so that a prefix of the basename may match one of the command names.
- Another option is first to extract the prefix (e.g. `/^[[:alpha:]]+/`) from the variable `applet` (which contains the basename) and to match the prefix with the command names.
- Or even another possibility is to track the processing of the symbolic link resolution: list up all the basenames including the intermediate steps of the link resolution, and find the earliest matching name on the …

[bin] Fix bin name detection

---

osh/word_eval.py
spec/array.test.sh

The current `master` crashes with the following command:
```console
$ bin/osh -c 'a=(1 2 3); echo "${a[@]: -7}"'
File "/home/murase/.mwg/git/oilshell/oil/bin/oils_for_unix.py", line 201, in <module>
File "/home/murase/.mwg/git/oilshell/oil/bin/oils_for_unix.py", line 170, in main
File "/home/murase/.mwg/git/oilshell/oil/bin/oils_for_unix.py", line 140, in AppBundleMain
File "/home/murase/.mwg/git/oilshell/oil/core/shell.py", line 1213, in Main
is_return, is_fatal = cmd_ev.ExecuteAndCatch(node, cmd_flags)
File …
```

[osh] Fix crash with `${a[@]: -(2*${#a[@]}+1)}`

---

core/state.py
spec/array.test.sh

In the current master, after unsetting the last element `unset -v a[-1]` when there is a hole before the last element, the subsequent call of array slice `${a[@]: -1}` fails to handle negative offset properly.
```console
$ bash -c 'a=(1); a[9]=x; unset -v "a[-1]"; echo "${a[@]: -1}"'
1
$ bin/osh -c 'a=(1); a[9]=x; unset -v "a[-1]"; echo "${a[@]: -1}"'
$
```

[osh] Fix last element `${a[@]: -1}` after `unset -v a[-1]`

---

osh/word_eval.py
spec/array.test.sh

The current `master` crashes with `${a[@]@Q}` when `a` has unset elements.
```console
$ bin/osh -c 'a=(x); a[2]=y; echo "${a[@]@Q}"'
File "/home/murase/.mwg/git/oilshell/oil/bin/oils_for_unix.py", line 202, in <module>
File "/home/murase/.mwg/git/oilshell/oil/bin/oils_for_unix.py", line 171, in main
File "/home/murase/.mwg/git/oilshell/oil/bin/oils_for_unix.py", line 141, in AppBundleMain
File "/home/murase/.mwg/git/oilshell/oil/core/shell.py", line 1213, in Main
is_return, is_fatal = cmd_ev.ExecuteAndCatch(node, …
```

[osh] Fix `${a[@]@Q}` crash with unset elements in array

---

core/bash_impl.py
core/state.py
spec/ble-idioms.test.sh

BigInt operations for comparison are done through `bash_impl.BigInt_Less` as suggested in Ref. [1]
[1] https://oilshell.zulipchat.com/#narrow/channel/121539-oil-dev/topic/2024-11-22.20Meeting/near/485124692
For the result of `SparseArray_GetElement`, there are three possible cases:
- An element is found at the specified index. In this case, we return the value.
- No element is found at the specified index. In this case, we return `None`.
- The index is invalid. In particular, this happens when the index is too negative as `((index < -n))` (where `n` is the max index plus 1). I would like to return an error status this case, and let the caller determine how to handle it.
~~In the current PR,~~ In the planned PR for `SparseArray_GetElement`, I return a tuple `(str result, int error_code)` …

[core/state] Implement SparseArray `a[i]=v`

---

spec/globstar.test.sh
test/spec.sh

Related to #232.
Following what Ellen did in #1757, I had to use some restrictive naming (foo.md) in my test cases to work around the `_tmp` (?) subdirectory. I don't understand what the testing environment looks like: if indeed the current directory during test execution is the repo root, I would expect some of my globs to pick up, say, `osh/bool_stat.py`.

[test/spec] Add failing globstar tests

---

core/dev.py
osh/cmd_eval.py
spec/xtrace.test.sh

In the current `master`, xtrace outputs wrong commands for `a+=(v)` and `declare a+=(v)` in respective ways. Both are two different bugs. This PR fixes both.
For `declare a+=()`, xtrace does not consider the type of the assignment `=` vs `+=`.
```console
$ bin/osh -c 'set -x; declare a+=(v)'
+ declare a=(v)
```
829dddec0 fixes this problem.
For `a+=(v)`, xtrace outputs the state of the array after the assignment as the value on the right-hand side.
```console
$ bin/osh -c 'a=(1); set -x; a+=(2)'
+ a+=(1 2)
```
8a586ab2d fixes this.

[core/dev] Fix xtrace output for `a+=(v)` and `declare a+=(v)`

---

core/state.py
frontend/typed_args.py
osh/sh_expr_eval.py

https://oilshell.zulipchat.com/#narrow/channel/121539-oil-dev/topic/mops.2EBigInt.28i.29.20vs.2E.20mops.2EIntWiden.28i.29/near/485491602
`mops.BigInt(c)` for constants are intentionally left.

[refactor] Use `mops.IntWiden` for "int -> BigInt" conversion

---

core/bash_impl.py
core/state.py
osh/word_eval.py

I here suggest changing the name `_Length` to `_Count`. This is because there are two types of "lengths" in arrays.  One is the count of elements.  The other is the max index plus one.  They differ for sparse arrays.  For example, for an array constructed by `a=(); a[0]=x a[9]=y`, the former is 2, while the latter is 10.  This PR suggests calling the former "count", and the latter "length".
Ref: original discussion: https://github.com/oils-for-unix/oils/pull/2161#issuecomment-2510146764
This PR also contains the fix for the error message of a negative out-of-bound index. I added the "array length" to the error message of the negative array index in [\#2160 `core/state.py`](https://github.com/oils-for-unix/oils/pull/2160/files#diff-947c57d83e952ecdb670a97c89273b980cf665a12fd551ef0dc2e2d4015 …

[refactor] Rename `${#arr[@]}` from `_Length` to `_Count`

---

core/bash_impl.py
core/state.py
spec/array.test.sh

This moves the codes for `unset -v 'a[i]'`.

[core refactor] Refactor the code for BashArray/BashAssoc `unset -v a[i]`

---

osh/sh_expr_eval.py
osh/word_eval.py
spec/array.test.sh

In the current master, they do not cause any error or warning.
```console
$ bin/osh -c 'a=(1); echo ${a[-2]}; echo $((a[-2]))'
0
```
while Bash produces warning messages (though they are just messages, and it does not cause any error):
```console
$ bash -c 'a=(1); echo ${a[-2]}; echo $((a[-2]))'
bash: line 1: a: bad array subscript
bash: line 1: a: bad array subscript
0
$
```
This PR checks the negative out-of-bound index in two cases `${a[i]}` and `$((a[-2]))` and outputs warning messages.

[osh] Check negative out-of-bound index for `${a[i]}` and `$((a[i]))`

---

core/bash_impl.py
ysh/val_ops.py

https://github.com/oils-for-unix/oils/pull/2167#discussion_r1866875583 in the existing codebase.
This removes unnecessary `.keys()` in for-loops. Those loops do not modify the iterated dictionary, so there shouldn't be a problem.

[refactor] Optimize dictionary iteration

---

core/bash_impl.py
core/runtime.asdl
core/state.py
osh/sh_expr_eval.py
osh/word_eval.py

> https://github.com/oils-for-unix/oils/pull/2167#discussion_r1866878249
>
> Also I think it would be nice to have
> 
> `if error == bash_impl.IndexOutOfRange`
> 
> instead of hard-coding `1` . Then we don't need the comment, and it is more readable
This introduces an enum type to return the error status of a negative out-of-bound index of indexed arrays. To add the enum, I added `error_code = OK | IndexOutOfRange` in `runtime.asdl` (which may be extended to include other types of errors in the future). If there is a better way, please let me know.

[core/bash_impl] Use `error_code_t` to return error

---

builtin/readline_osh.py
pyext/line_input.c
spec/builtin-bind.test.sh
spec/stateful/bind.py

OK, this was pretty easy, as I suspected. The older method of unbinding still works; it's essentially like "binding" the keyseq to a null pointer, which readline interprets as wanting to remove the binding.
This is based off bash code added in 4.1 from 2011. The newer version is from bash 5.0 from 2019.
IIUC, this is slightly less efficient code, but no big deal. I left the newer code in place, but commented out. LMK if you want to remove it. Otherwise, I thought I'd delete it once the final pieces of bind -x are complete, and we're all done.
----
I added a non-interactive test for `bind -r`. We can use `bind -q` to see what readline thinks the bindings are, but this can't test that the binding behavior is actually removed.
I incremented oils_cpp_failures_allowed, since I'm assuming the …

Fix `bind -r` support with older readline fns

---

core/bash_impl.py
osh/sh_expr_eval.py
osh/word_eval.py

This PR includes four commits.
- 81c37b43a7d2ae466f9dc517e134e367105a6556 renames an existing function `word_eval.GetArrayItem` to `bash_impl.BashArray_GetElement`.
- 6315b5d3fd8c357411cd7341747823370dd0221a adds `BashAssoc_GetElement` and uses it for `${assoc[key]}` and `$((assoc[key]))`.
- b0b16916c98d8a4552aaad30a6d7848f6c51bca6 uses `Bash{Array,Assoc}_GetElement` for `$arr` (which is equivalent to `${arr[0]}`).
- 9b7b2e3ee08f46ff389733df7d6476df57c25f78 is a refactoring of `bash_impl` using a new function `_BashArray_CanonicalizeIndex` (similar to the one for sparse arrays).

[osh] Refactor BashArray/BashAssoc `${arr[i]}`, `$((arr[i]))`, and `$arr`

---

osh/word_eval.py

This does not change the behavior, but it is inconsistent that `BashAssoc` is not checked, while `BashArray` is explicitly checked. `BashAssoc` has been slipped off from the type check due to the missing `else:` branches.
**edit**: This PR also contains commits for removing unused variable (3016835c08bcc5f31fa964fedde1349b8e0ef296) and reducing the mostly identical code (b82072650427848e2cb38a299721f99e11aef0a5).
**edit**: I realized that non-OSH/Bash objects (such as `List`, `Dict`, and `Float`) may go through this function in YSH even though `${a[@]}`, etc. are not supported for those objects. In commit 88301b1d5618406941e75b9f1a9d97cab8b2ce2f, I changed the check to be permissive for unknown types with a code comment.

[refactor] Explicitly let BashAssoc/SparseArray pass through for `${a[@]}`

---

builtin/func_misc.py
builtin/method_str.py
core/bash_impl.py
core/completion.py
frontend/reader.py
osh/sh_expr_eval.py
ysh/expr_eval.py
ysh/val_ops.py

https://oilshell.zulipchat.com/#narrow/channel/121539-oil-dev/topic/2024-11-22.20Meeting/near/486625799
There are two declarations of the form `v = None  # type: str` and `v = None  # type: Optional[str]`. This PR unifies them to `v = None  # type: Optional[str]`.
- 35481d91f1b476f248dacda352e157197d91c3e7 is fixes for the codes I contributed.
- 9493b3b1d is the fixes for the trivial case: rewriting from `= None  # type: str` to `= None  # type: Optioanl[str]`
I tried to find non-trivial cases where the variable is first assigned with an object and then with `None`, but it seems in most cases, the object assigned first has a class type. I haven't checked all the files, but I decided not to fix these non-trivial cases within this PR.

[refactor] Use `Optional[str]` instead of `str` when `None` is possible

---

core/bash_impl.py
osh/cmd_eval.py
osh/word_eval.py

This PR includes a set of refactoring changes for `${a[@]...}` for BashArray/BashAssoc. See respective commits.

[osh refactor] Refactor BashArray/BashAssoc `$*`, `${a[@]}`, `${a[@]#...}`, `${a[@]//pat/sub}`, `${a[@]:offset:len}`, and `${a[@]@Q}`

---

core/bash_impl.py
osh/word_eval.py

This is probably the last PR for the BashArray/BashAssoc refactoring with `bash_impl` for **the OSH sector**. There are still places related to **YSH** and **serialization** (JSON, pretty printing, etc.), where implementation details of BashArray/BashAssoc are assumed.

[osh refactor] Refactor BashArray/BashAssoc `${!arr[@]}`

---

spec/ble-idioms.test.sh
ysh/val_ops.py

Note: `SparseArray_GetValues` does not preserve the unset elements, but we can use it here (`val_opts.ToShellArray`) because the `None` elements will be ignored in the callers anyway: The function `val_opts.ToShellArray` is used to generate a list of words by `expr_eval.ExprEvaluator.{EvalExprSub,SpliceValue}`. These functions are used by `word_eval.AbstractWordEvaluator.EvalWord*` through `word_eval.AbstractWordEvaluator._EvalWordPart`.  The resulting array is processed by `word_eval._MakeWordFrames`, where `None` elements are ignored.

[ysh] Implement SparseArray `@[sp]` and `@sp`

---

core/bash_impl.py
osh/word_eval.py
spec/ble-idioms.test.sh

This PR actually largely rewrites the handling of the BashArray slicing together.
The second commit adds the support for BigInt *offset* in the construct `${a[@]:offset:count}`.

[osh] Implement SparseArray `${a[@]:offset:count}`

---

test/sh_spec.py

This is a trivial fix. In the current master, the error message for the error count shows a different number for the allowed C++ failures.

[test/sh_spec] Fix error message for C++ failures

---

spec/arith.test.sh
spec/assign-extended.test.sh
spec/ble-features.test.sh
spec/brace-expansion.test.sh
spec/bugs.test.sh
spec/builtin-printf.test.sh
spec/builtin-read.test.sh
spec/dparen.test.sh
spec/loop.test.sh
spec/parse-errors.test.sh
spec/toysh-posix.test.sh
spec/var-op-len.test.sh
spec/var-op-slice.test.sh
spec/xtrace.test.sh
test/sh_spec.py

This PR picks a part of #2192 to add checks for inconsistent spec tests.
fa625e262
- Check duplicate test spec definitions. For example, when the `STDOUT` section is specified multiple times for a specific shell, we produce an error message.
- Properly handle multiple levels of failure (`OK`, `BUG`, `N-I`, etc.). In the current master, when both `BUG` and `OK` requirements are specified for a specific shell, and when the `OK` requirement is specified later, the result shown in the table becomes `OK`. In this commit, we change it to choose the worst failure level. For example, when the shell satisfies the `BUG` and `OK` requirements, we show `BUG` in the table.
- This commit also modifies existing inconsistent test spec definitions
08cd83827
- In the current master, the filename is not …

[test/sh_spec] Handle duplicate/conflicting test spec definitions

---

core/runtime.asdl
osh/word_eval.py
spec/var-op-bash.test.sh

This PR refactors and simplifies the existing code for checking `nounset`. This also fixes the regression of `${undef@P}` and `${undef@Q}` mentioned in #2186:
> https://github.com/oils-for-unix/oils/pull/2186#issuecomment-2537311633 @akinomyoga 
>
> > then change the test to
> > ```
> >            if not vsub_state.has_test_op and not vsub_state.has_nullary_op:
> >                 val = self._EmptyStrOrError(val, part.token)
> > ```
> >   
> > and then for `@Q` and `@P`, handle `case(value_e.Undef)` in the normal way, producing empty string
> 
> This change breaks `osh -uc "${undef@P}"` and `osh -uc "${undef@Q}"`. The `nounset` check is skipped.
>
> https://github.com/oils-for-unix/oils/pull/2186#issuecomment-2537349028 @andychu 
>
> Ahh we are missing test coverage for `-u` ? OK thank …

[osh] Fix regression of `${undef@P}` and `${undef@Q}` with `nounset`

---

doc/ref/chap-word-lang.md
doc/ref/toc-osh.md
osh/word_eval.py
spec/var-ref.test.sh

- **PR(a)** I wanted to submit a PR for SparseArray `${sp[@]...}`
- **PR(b)** However, the behaviors of existing BashArray/BashAssoc `${a[@]@Q}` and `${a[@]@a}` are broken, and `${a[@]@P}` is not implemented. So I first need to fix the behaviors of BashArray/BashAssoc `${a[@]@?}`.
- **PR(c)** However, before fixing the above behavior, BashArray/BashAssoc `${a@a}` and `${a[0]@a}` need to be fixed because it implements something different from Bash's.
- **PR(d)** Then, I tried to fix the above. However, I realized that even another incomplete behavior conflicts. `${!a[@]...}` should perform the indirect expansion, though `osh` tries to generate the keys of `a`.
This PR is **PR(d)** in the above chain. In the current master, osh interprets e.g. `${!a[@]...}` in a completely different way …

[osh] Perform indirect expansion with `${!a[@]...}`

---

osh/word_eval.py
spec/var-op-test.test.sh
spec/var-ref.test.sh

This PR upgrades the spec tests in `var-ref` from bash-4 to bash-5 (dfc8fd8cc).
In addition, we change the behavior of `${!undef[@]-}` to match the behavior fixed in Bash 5 (7baa3a74d).
I wrote in https://github.com/oils-for-unix/oils/pull/2201#issuecomment-2563150818 that I would work on https://github.com/oils-for-unix/oils/pull/2201#discussion_r1897976186 and https://github.com/oils-for-unix/oils/pull/2201#discussion_r1897976947, but I decided to separate it from this PR because it seems to affect a wider range of behavior for `${!ref}` in general.

[osh] Follow the Bash change in `${!undef[@]-}`

---

core/state.py
spec/testdata/module2/main.ysh
spec/ysh-builtin-module.test.sh

Previously, is-main would succeed in a module sourced via use

[ysh] Fix is-main when combined with use

---

builtin/pure_ysh.py
core/bash_impl.py
spec/ble-idioms.test.sh
ysh/val_ops.py

Each commit corresponds to `$[sp1 === sp2]`, `append ... (sp)`, or `$[bool(sp)]`.

[ysh] Implement SparseArray `$[sp1 === sp2]`, `append ... (sp)`, and `$[bool(sp)]`

---

core/runtime.asdl
doc/ref/chap-word-lang.md
osh/word_eval.py
spec/var-op-bash.test.sh

This corresponds to "**PR(c)**" explained in #2201. I'll submit the changes for **PR(b)** after settling this change.
I noticed that the behavior for `${a[0]@a}` is different from Bash:
* In Bash, `a` and `A` are used to mark the nature of **a string placeholder** (i.e., either a *scalar variable* or an *array element*), so `${a[0]@a}` generates `a` and `A` for indexed and associative arrays, respectively.
* However, in osh, `a` and `A` are used to mark the type of **an obtained value** (e.g., an empty string for a scalar variables, and `a` or `A` for word lists originating from indexed and associative arrays), so `${a[0]@a}` generates a empty string because `a[0]` is not an entire array.
I think the existing code comments in the osh codebase imply that the difference is intentional. …

[osh] Return the placeholder type for `${a@a}` and `${a[0]@A}`

---

builtin/completion_osh.py
spec/builtin-completion.test.sh

There are two crashes with `compadjust`.
----
With the current `master` branch,
```console
$ bin/osh -c 'COMP_ARGV=(); compadjust cur words'
File "/home/murase/.mwg/git/oilshell/oil/bin/oils_for_unix.py", line 202, in <module>
File "/home/murase/.mwg/git/oilshell/oil/bin/oils_for_unix.py", line 171, in main
File "/home/murase/.mwg/git/oilshell/oil/bin/oils_for_unix.py", line 141, in AppBundleMain
File "/home/murase/.mwg/git/oilshell/oil/core/shell.py", line 1213, in Main
is_return, is_fatal = cmd_ev.ExecuteAndCatch(node, …
```

[builtin] Fix `compadjust` crashes with empty and sparse `COMP_ARGV`

---

core/completion.py
spec/builtin-completion.test.sh

With the current `master` branch,
```bash
$ bash -c '_test() { unset -v COMPREPLY; COMPREPLY=hello; }; compgen -F _test 2>/dev/null'
hello
$ bin/osh -c '_test() { unset -v COMPREPLY; COMPREPLY=hello; }; compgen -F _test 2>/dev/null'
$
```
This also includes a refactoring commit da6a6c168f354aed621384fd2adb6766aaaed24b. After that, the main change is introduced in commit 87c4e626f77a159a2ea17b35ed050cf5be3bf2b9.

[core/completion] Support scalar `COMPREPLY` with `compgen -F`

---

osh/prompt.py
osh/prompt_test.py
osh/word_eval.py
spec/prompt.test.sh
spec/var-op-bash.test.sh
spec/var-ref.test.sh

This corresponds to **PR(b)** explained in #2201.
* In Bash, for the same reason as described in #2208, `${a[@]@a}` generates `a a ... a` and `A A ... A` for indexed and
associative arrays, respectively.
* In osh, for the same reason as described in #2208, `${a[@]@a}` generates single words `a` and `A` for indexed and
associative arrays, respectively, because osh returns the type of the entire array.
This PR also includes the modification to `@Q`. Also, `@P` was only supported for a scalar variable, but now this PR implements it for BashArray/BashAssoc. 03cf713b2 is a related refactoring commit.

[osh] Implement `${a[@]@P}` and make `${a[@]@a}` and `${a[@]@Q}` consistent with Bash

---

spec/var-op-bash.test.sh

https://github.com/oils-for-unix/oils/pull/2210#discussion_r1901061335
I split the test into three, but it seems non-trivial to normalize the results so that the expected STDOUT can be shared. It is because, to normalize the results (particularly for the hash ordering), one needs to assume the form of the results, which is actually the test target. In this PR, I just split the tests and reduced the OK sections for the tests with the common results. I think this is sufficient because it is now easy to compare these smaller OK sections with the corresponding PASS sections.

[spec/var-op-bash] Split #24 into respective tests for `@Q`, `@P`, and `@a`

---

osh/word_eval.py
spec/ble-idioms.test.sh

This corresponds to **PR(a)** in #2201. Each commit in this PR corresponds to a feature of the form `${sp[@]...}`.

[osh] Implement SparseArray `${sp[@]...}`

---

mycpp/mark_sweep_heap.h

The constructor declaration/definition of the form `template<typename T> class C { C<T>(); }` is removed in C++20. This causes many compiler warnings in recent compilers. One can always declare it without template arguments (in any C++ versions): `template<typename T> class C { C(); }`.

[mycpp] Fix constructor with template arguments deleted in C++20

---

osh/cmd_eval.py
spec/append.test.sh

In the current `master` branch,
```console
$ bin/osh -c 's= s+=([a]=b)'
File "/home/murase/.mwg/git/oilshell/oil/bin/oils_for_unix.py", line 202, in <module>
File "/home/murase/.mwg/git/oilshell/oil/bin/oils_for_unix.py", line 171, in main
File "/home/murase/.mwg/git/oilshell/oil/bin/oils_for_unix.py", line 141, in AppBundleMain
File "/home/murase/.mwg/git/oilshell/oil/core/shell.py", line 1213, in Main
is_return, is_fatal = cmd_ev.ExecuteAndCatch(node, cmd_flags)
File …
```

[osh] Fix crashes with `s+=([0]=v)`, `a+=([0]=v)`, and `assoc+=(0)`

---

doc/ref/chap-type-method.md

was testing the docs to set myself a custom prompt as described in ~/.config/oils/yshrc and ran into:
```
<Runtime error: Attribute 'promptval' not found on Obj>
```

[doc] Fix promptVal example

---

spec/stateful/bind.py
test/stateful.sh

These are the initial stateful tests for `bind -x` behavior.
I'm not clear yet on how to test changes to the READLINE_* envvars. I'm somewhat sure that READLINE_LINE changes would be reflected in the stream for pexpect, but afaict, pexpect has no concept of a cursor to even begin to test changes to READLINE_POINT.
I'm ignoring for now, since those are less important use cases.

Stateful spec tests for `bind -x` behavior

---

test/sh_spec.py

I ran into this little thing when I was running new test cases and was accidentally checked out to the wrong branch. It ran 0 cases and exited normally and I was confused.

`sh_spec.py` check for range out of bounds

---

spec/prompt.test.sh

https://github.com/oils-for-unix/oils/issues/2235

add tests for all bash prompt special characters

---

build/ninja-rules-cpp.sh

https://github.com/oils-for-unix/oils/commit/42f197eb2c397ce7dc89c270173383a3797837a1, which fixes https://github.com/oils-for-unix/oils/issues/2227 is fighting with `errexit` because of a bug
in bash 3.2 (the default on lots of macos installations). This commit
updates the affected build script to skip timing alltogether on bash 3.x
release to avoid weird behavior.

fix time -f check interaction with errexit

---

core/comp_ui.py
core/comp_ui_test.py
core/shell.py
frontend/flag_def.py

There are three commits here. One makes it so only the nice completion display sets `horizontal-scroll-mode`. This should help with #2081. The other changes the display style of the minimal completion display. Instead of only printing a subset of matches in a single column and saying that there are more, we now just print them all in the packed format. This behavior will be more similar to what bash users are familiar with and just generally more useful. The last change makes the minimal completion display the default. This should minimize friction for newcomers.

make minimal completion display more bash-like

---

core/shell.py
doc/ref/chap-special-var.md
doc/ref/toc-osh.md
doc/ref/toc-ysh.md
test/manual.sh

This will be more user-friendly than the existing command-line arg, since people can set it in their init files.

add OILS_COMP_UI

---

builtin/method_list.py
core/shell.py
demo/survey-list.sh
doc/ref/chap-type-method.md
doc/ref/toc-ysh.md
mycpp/gc_list.h
mycpp/mops.py
spec/ysh-list.test.sh

Add missing `List->remove()` and `List->insert()` methods.
Please do suggest improvements to tests. I'm also assuming that mirroring the behaviour of python's remove and insert methods is alright.

[ysh] implement List remove() & List insert()

---

core/runtime.asdl
osh/word_eval.py
spec/toysh-posix.test.sh
spec/word-split.test.sh
ysh/expr_eval.py

Please see the commit message for the details.
This fixes an issue discussed in DM (Koichi Murase, Andy Chu, 2025-02-16) about the behavior of `$*` with `IFS=`. A related discussion is https://oilshell.zulipchat.com/#narrow/channel/121539-oil-dev/topic/How.20other.20shells.20implement.20IFS.
By the way, in the testing, I found Bash bugs: `${!prefix*}` and `${!arr[*]}` doesn't follow the rule with `IFS=`, as others `$*` and `${a[*]}` (See the added test cases, spec/word-split 39 and 40).

[osh] Fix unquoted `$*`, `${*}`, `${a[*]}`, etc. under empty IFS

---

spec/toysh-posix.test.sh
spec/word-split.test.sh

These are follow-up fixes for #2248. This PR also contains a fix to another broken test case: 0187f3bb62f2b0375c789f089a899c988d554673, where `=` of an assignment was missing.
----
Bash's behavior `IFS=x` seems strange to me (see the added test case, where the number of arguments decreases by one every time resetting them). However, even if we report it to the upstream Bash, I guess Chet wouldn't finally change the behavior. This area is the one marked as "*unspecified*" by POSIX, and the behavior among the shells is anyway not consistent. In addition, as far as I look at the codebase of Bash, the fix wouldn't be simple. It would require rewriting multiple places in the Bash codebase. In addition, I guess the impact on the real use cases wouldn't be so significant.
Except for `bash` and …

[spec/word-split] Add more failing test cases for `IFS=x; set "" "" ""; $*`

---

core/bash_impl.py
spec/ble-idioms.test.sh

For a smoother transition of the indexed-array internal representation from `BashArray` to `SparseArray`, I here suggest switching the printed form of `SparseArray` (used by `declare -p` and other places) based on whether it is indeed "sparse" or not.
- The current behavior of `SparseArray`:
- It always uses the designated array initializer form: `([0]=1 [1]=2 [4]=5 ...)`
- This PR modifies the behavior as follows:
- When it is dense (i.e., when all the indices up to `max_index` are filled), it would use the same printed form as the present `BashArray`: `(1 2 3 4 5 ...)` 
- When it is sparse (i.e., when there is a "hole"), it would use the designated array initializer form: `([0]=1 [1]=2 [4]=5 ...)`
Even though we currently do not support the designated initializer syntax …

[bash_impl] SparseArray: omit index in the printed form in the dense case

---

builtin/assign_osh.py
builtin/func_misc.py
builtin/pure_ysh.py
core/bash_impl.py
core/completion_test.py
core/state.py
core/state_test.py
osh/sh_expr_eval.py
osh/word_eval.py
spec/array-compat.test.sh
spec/array.test.sh
spec/assign-extended.test.sh
spec/ysh-builtin-meta.test.sh
spec/ysh-builtins.test.sh
spec/ysh-expr-bool.test.sh
spec/ysh-expr.test.sh
spec/ysh-json.test.sh
spec/ysh-printing.test.sh
spec/ysh-with-sh.test.sh

This PR changes the default indexed array representation from `BashArray` to `SparseArray`.
This PR also includes the adjustments to the spec test cases. Some of the rewrite will finally be *effectively* reverted on the renaming of SparseArray to BashArray, but to avoid confusion and inconsistency, we anyway properly update them. For the same reason, this PR also includes adjustments to the error messages. Those error messages will also be somehow reverted, but we want to include the adjustments to error messages within this PR to make the later renaming PR consistent.
This PR doesn't completely remove the use of `BashArray` because it seems to make more sense to use the simpler representation for some specific internal uses. For example, in processing `"$@"` and `"${a[@]}"`, they are …

[osh] switch the default indexed array from `BashArray` to `SparseArray`

---

test/ble.sh

I rebased the `osh` branch in the upstream `akinomyoga/ble.sh` on the latest version of `ble.sh`.  As a consequence, sourcing `out/ble.osh` in the CI has started to fail (see Run 9147's [`ble-test-osh-py.txt`](https://op.oilshell.org/uuu/github-jobs/9147/app-tests.wwz/_tmp/soil/logs/ble-test-osh-py.txt) and [`ble-test-osh-cpp.txt`](https://op.oilshell.org/uuu/github-jobs/9147/app-tests.wwz/_tmp/soil/logs/ble-test-osh-cpp.txt)).
The latest version of `ble.sh` checks whether the current session has an associated TTY when loaded as an interactive setting.  When `ble.sh` cannot detect the TTY, it cancels its loading.  To load `ble.sh` in a non-interactive session, one needs to source `ble.sh` using "the library mode" by specifying the option `--lib`.

[test/ble.sh] Add "--lib" in loading "out/ble.osh"

---

builtin/assign_osh.py
spec/assign.test.sh

There is a dead code:
https://github.com/oils-for-unix/oils/blob/24146f4b0a223354c5f2e42e59cad00358ff82a5/builtin/assign_osh.py#L322-L334
The value of `rval` calculated in the above lines is not used anywhere. The next line only uses the original value `pair.rval`:
https://github.com/oils-for-unix/oils/blob/24146f4b0a223354c5f2e42e59cad00358ff82a5/builtin/assign_osh.py#L339
This is a regression introduced in [this hunk in commit `fd47f77`](https://github.com/oils-for-unix/oils/commit/fd47f772e49b2217c603a834e0521227e6ec2759#diff-81b973a51b80c984cbe64b92eb65bc97b31b7ce89fcd54920b7ed952410e3e85L291).
In fact, we can confirm that the `readonly` builtin doesn't behave in the expected way:
```console
$ bin/osh -c 'declare -a a; declare -p a'
declare -a a=()
$ bin/osh -c 'declare -A a; declare …
```

[builtin/assign_osh] Fix `readonly` failing to create arrays with -a/-A

---

osh/cmd_eval.py

Before implementing the initializer-list approach to the assignment of the form `name=(...)`, I'd like to confirm the assumptions in the relevant places in the codebase.
In the function `cmd_eval._DoShAssignment`, there is a code path to handle the case where the RHS of ShAssignment is None, but is there a real case for it? The shell assignments should always have the form `var=rhs`. Even if `rhs` is empty, it should still generate an empty string as a RHS.
As far as I quickly checked the code, the RHS seems ensured to be not None. In this PR, I attempt to assert it never happens and see if the assertion passes the CI.

[refactor osh/cmd_eval] Assert RHS of `ShAssignment` is not `None`

---

builtin/assign_osh.py

The first commit is the main change. There is a duplicate code in `NewVar`. For `Readonly` and `Export`, a code to perform an assignment to a single variable is factorized into a function `_ExportReadonly`, but `NewVar` also has the same code. This PR modifies `NewVar` to use `_ExportReadonly` (with a small adjustment to switch scope).
The second commit is an extra commit renaming `_ExportReadonly` to `_AssignVarForBuiltin`. The name `_ExportReadonly` seems to have been named only after the fact that it is used by `export` and `readonly`, which doesn't explain what this function does. If we need to continue this naming, we need to update it to be `_ExportReadonlyNewVar` this time, which seems clumsy.

[refactor builtin/assign_osh] Remove duplicate codes in `NewVar`

---

builtin/assign_osh.py
core/bash_impl.py
core/state.py
spec/ble-sparse.test.sh

Fixes #2263.
This fixes an issue of #2263. This also fixes another issue https://github.com/oils-for-unix/oils/issues/2263#issuecomment-2677382000. In the previous versions, `unset[-1]=1` has created `unset=(1)` in the Python version and has core-dumped in the C++ version.
```console
$ bash -c 'unset[-1]=1; declare -p unset'
bash: line 1: unset[-1]: bad array subscript
$ bin/osh -c 'unset[-1]=1; declare -p unset'
declare -a unset=(1)
$ osh-0.27.0 -c 'unset[-1]=1; declare -p unset'  # 0.27.0 C++ version
Segmentation fault         (core dumped) osh-0.27.0 -c 'unset[-1]=1; declare -p unset'
```
The last commit 069162fd6 adds a spec test for the above bug.
This PR contains another commit a271b53c61b69413d53e136511131f13ccc4a413 to refactor the creation of a new sparse array. We've been passed …

[core/state] Do not initialize a sparse array with a long `List[str]`

---

builtin/assign_osh.py
core/bash_impl.py

This is another preparation for the initializer-list implementation.
This PR adds `bash_impl.BashAssoc_New` so that the implementor doesn't have to care about `NewDict` in creating an instance of `BashAssoc`. This is also make it consistent with the `BashArray` creation through `BashArray_New` introduced in #2268.

[refactor core/bash_impl] Add `BashAssoc_New`

---

osh/word_parse.py
spec/ble-idioms.test.sh

The right-hand side of `[k]=rhs` in the list assignment `a=([k]=v)` is subject to the tilde expansion. However, the current `master` doesn't perform it:
```console
$ bash -c "declare -A a=([k]=~); echo \"\${a['k']}\""
/home/murase
$ bin/osh -c "declare -A a=([k]=~); echo \"\${a['k']}\""
~
```
It should be noted that Bash 5.2 has a similar bug. It is fixed in Bash 5.3.
```console
$ bash-5.1 -c "declare -A a=([k]=~); echo \"\${a['k']}\""
/home/murase
$ bash-5.2 -c "declare -A a=([k]=~); echo \"\${a['k']}\""
~
$ bash-5.3 -c "declare -A a=([k]=~); echo \"\${a['k']}\""
/home/murase
```

[osh/word_parse] Perform tilde expansion on `rhs` of `dict=([key]=rhs)`

---

builtin/assign_osh.py
spec/assign.test.sh

In the current `master`, `readonly -a a` and `readonly -A a` remove existing indexed and associative arrays, respectively. See the following example:
```console
$ bash -c 'a=(1 2 3); readonly -a a; declare -p a'
declare -ar a=([0]="1" [1]="2" [2]="3")
$ osh -c 'a=(1 2 3); readonly -a a; declare -a a'
declare -ra a=()
```
This PR fixes the above behavior by initializing an empty array only when an existing value has a different type from the one expected by `-a` or `-A`. This behavioral change is similar to the one for the `declare` builtin introduced in #731.
Actually, this behavior of removing the existing arrays has been hidden under another bug fixed in #2265. Now #2265 was merged, and this problem has been revealed.
----
This patch moves the adjustment of the value into the function …

[builtin/assign_osh] Do not remove existing arrays with `readonly -a/-A`

---

osh/word_.py
spec/array.test.sh

I think this should anyway be fixed when InitializerList is introduced, but I'd like to confirm the intended behavior. In the current osh, arrays of the form `(1 2 3)` (`ShArrayLiteral`) cannot be specified in tmpenv, but the form `([k]=v)` (`BashAssocLiteral`) can be specified:
```console
$ osh-0.27.0 -c 'A=(a a) declare -p A'
A=(a a) declare -p A
^~
[ -c flag ]:1: Environment bindings can't contain array literals
$ osh-0.27.0 -c 'A=([a]=a) declare -p A'
declare -A A=(['a']=a)
```
I think `BashAssocLiteral` should also be rejected for consistency.

[osh/word_] Disallow `BashAssocLiteral` in temporary environment

---

builtin/assign_osh.py
core/state.py
osh/cmd_eval.py
osh/sh_expr_eval.py
spec/assign.test.sh

In the current `osh`, readonly arrays can be modified using `a+=(...)`:
```console
$ bash -c 'readonly -a a=(1 2 3); declare -p a; eval "a+=(4)" 2>/dev/null; declare -p a'
declare -ar a=([0]="1" [1]="2" [2]="3")
declare -ar a=([0]="1" [1]="2" [2]="3")
$ osh-0.27.0 -c 'readonly -a a=(1 2 3); declare -p a; eval "a+=(4)" 2>/dev/null; declare -p a'
declare -ra a=(1 2 3)
declare -ra a=(1 2 3 4)
```
----
- The first commit 808a628c8 makes `sh_expr_eval.OldValue` receive a new argument `blame_loc` and resolves the following TODO:
https://github.com/oils-for-unix/oils/blob/a3b3a609bec59b159ab4f90c432613fdb7d1bc27/osh/sh_expr_eval.py#L132
- The second commit 6bd51d50c fixes the issue that readonly arrays can be modified by `a+=(...)`.

[osh/sh_expr_eval] Check `readonly` before modifying the object

---

test/spec-runner.sh
test/spec.sh

After 7338375e7294123cc2f0875ad50d77a23fa1926c, arguments to `test/spec.sh <name>` are ignored. For example, when I want to run a specific spec test, all tests are run:
```console
$ test/spec.sh ble-idioms -r1
ble-idioms.test.sh
case    line    bash    zsh     mksh    ash     osh
0       3     pass    pass    pass    FAIL    pass    recursive arith: one level
1      11     pass    pass    pass    FAIL    pass    recursive arith: two levels
2      19     pass    pass    BUG     FAIL    pass    recursive arith: short circuit &&, ||
3      49     pass    pass    pass    FAIL    pass    recursive arith: short circuit ?:
4      69     pass    BUG     pass    FAIL    pass    recursive arith: side effects
5      79     pass    pass    N-I     N-I     pass    recursive arith: recursion
6      88 …
```

[test] Fix `test/spec-runner.sh gen-task-file`

---

builtin/assign_osh.py
doc/ref/chap-osh-assign.md
spec/array-literal.test.sh

https://github.com/oils-for-unix/oils/pull/2279#discussion_r1976468318
This makes the behavior consistent with Bash.

[builtin/assign_osh] Disallow overwriting existing BashArray/BashAssoc

---

builtin/assign_osh.py
doc/ref/chap-osh-assign.md
osh/cmd_eval.py
spec/append.test.sh
spec/array-literal.test.sh

In Bash, string variables can always be used as if it is an array. This is also the case with `str+=(1 2 3)`, which converts the string variable to an array and modifies the content.

[osh] Promote a string to an array with `str+=(...)`

---

spec/stateful/bind.py
spec/stateful/harness.py
test/spec_lib.py
test/stateful.sh

This adds automatic interactive tests of the READLINE_* env vars for `bind -x`.
- Add dependency on [pyte](https://github.com/selectel/pyte), as suggested in the pexpect docs.
- Switch to raw r-strings for escaping to simplify and silence linter warnings
- Switch to single-character command sequences 
- Disable pexpect echoing in constructor instead of right afterwards with `setecho`
- Add LINES and COLUMNS environment variables for interactive tests, and associated `--num-lines` and `--num-columns` opts
In order to use pyte, it requires size params to emulate a terminal of given dimensions. pexpect defaults to 24 lines X 80 columns, which is fine, but it doesn't expose that anywhere (otherwise I would have used it).
How should we set, and share, the dimension info, which is needed by …

Add and expand bind -x `READLINE_*` env var tests

---

doc/ref/chap-type-method.md

The strings were missing `\n`! I also formatted it as if it was `= r` removing the spaces.

docs: fix captureAll output strings

---

build/deps.sh

Running the one-time setup does not currently work on a fresh Alpine install.
Currently, "coreutils" is needed for some advanced usage of "xargs". "findutils" is needed for some advanced usage of "date".

[deps] Add more required wedge dependencies for Alpine

---

doc/ref/chap-stdlib.md
stdlib/ysh/args-test.ysh
stdlib/ysh/args.ysh

Ref: [#oil-dev > A missing feature in args.ysh?](https://oilshell.zulipchat.com/#narrow/channel/121539-oil-dev/topic/A.20missing.20feature.20in.20args.2Eysh.3F/with/526243441)

args.ysh: Add support for flag escaping via --

---

builtin/assign_osh.py
spec/assign.test.sh

From private communication:
> While checking one of my WIP branches, I noticed that var d = {}; declare -p d produces declare -- d, which appears to be an unset value of the variable d. This is an intersection area of OSH and YSH, so this isn't a copatibility issue, but I'm not sure if the current design makes sense. What do you think?
>
> Andy Chu: Oh yes, I think I noticed that too
> I think we could "pretend d doesn't exist"?  Just not print itAndy Chu: Because there is no way to express it with the declare -p syntax ...

[builtin/assign_osh] Do not print variable name for unknown types

---

osh/word_eval.py
spec/word-split.test.sh

Bug 1: word splitting is applied to `${!prefix*}` inside quoted string `"..."`
```console
$ bash -c 'IFS=x axb=1; echo "${!axb*}"x'
axbx
$ bin/osh -c 'IFS=x axb=1; echo "${!axb*}"x'
a bx
```
Bug 2: word splitting is not applied to `${#v}`
```console
$ bash -c 'IFS=5 v=hello; echo [${#v}]'
[ ]
$ bin/osh -c 'IFS=5 v=hello; echo [${#v}]'
[5]
```
Bug 3: word splitting is applied to `${v:-val}` inside quoted string `"..."`
```console
$ bash -c 'IFS=x v=; echo "${v:-axb}"x'
axbx
$ bin/osh -c 'IFS=x v=; echo "${v:-axb}"x'
a bx
```

[osh/word_eval] Fix word-splitting bugs

---

builtin/read_osh.py
core/process_test.py
core/pyos.py
cpp/core.h
doc/ref/chap-builtin-cmd.md
spec/builtin-read.test.sh

Bug: `read -n 4` should not repeat `_ReadPortion` even if the previous read ended with incomplete backslash
```console
$ bash -c 'echo "abc\def\ghijxxxx" | (read -n 4; declare -p REPLY)'
declare -- REPLY="abcd"
$ bin/osh -c 'echo "abc\def\ghijxxxx" | (read -n 4; declare -p REPLY)'
declare -- REPLY=abcdefghij
```
Bash behavior: Counting of `read -n 5` should exclude escaping backslash
```console
$ bash -c 'echo "a\b\c\d\exxxx" | (read -n 5; declare -p REPLY)'
declare -- REPLY="abcde"
$ bin/osh -c 'echo "a\b\c\d\exxxx" | (read -n 5; declare -p REPLY)'
declare -- REPLY=abc
```

[builtin/read_osh] read -n respects backslashes when not -r, and other fixes

---

core/executor.py
frontend/syntax.asdl
osh/cmd_eval.py
osh/cmd_parse.py
osh/cmd_parse_test.py
spec/assign.test.sh
spec/redir-order.test.sh
spec/toysh-posix.test.sh
tools/ysh_ify.py

Fixes: https://github.com/oils-for-unix/oils/issues/2307
Need to clean-up a bit more, but this should fix the issue. Want to check its impact on other tests first.
---

Evaluate command.Simple argv before redirects

---

spec/divergence.test.sh

gzip has a utility script called zdiff. It gets used at some point in the check step when building gzip from source. It also makes use of nested subshells in a few places. The osh parser is tripping over these. Here's an example from a simple script.
((echo foo) | tr o 0)
^~~
_tmp/foo.sh:1: Unexpected token after arithmetic expression (Id.Word_Compound != Id.Arith_RParen)
Other shells seem to handle this case, so in preparation for an inbound fix, this commit adds a new spec test to cover it.
Related to #2398

add spec test for nested subshell parse error

---

regtest/aports-common.sh
regtest/aports-run.sh
regtest/aports-setup.sh
regtest/aports.md

As discussed in Zulip, a way to build all packages completely independently. This doesn't use `xargs ...` yet, so definitely needs more improvements. But my local test with a bunch of packages seemed to work. The only questionable thing: I can't tell how much overhead it creates.
A quick test showed that `aaudit` builds in about 2.5 seconds with `overlayfs` and about 2 seconds without. But that could just be the preparation, in which case it would mean that there is about half a second added per package, which is about 15mins additional time required. If it's overhead at build time, well, then it will probably take longer :)

feat: new build option 'build-packages-overlayfs'

---

regtest/aports-setup.sh

This will make interactively debugging bugs inside the chroot much easier.
The paths all lined up, so our `configure` picks this up without any extra changes.
```
$ enter-overlayfs-user osh-as-sh.overlay
~ $ history
0 history
1 ls
2 history
3 set -o vi
4 vim
5 vi
6 clear
7 ls
8 history
(reverse-i-search)'set': set -o vi
```

aports: install readline-dev in chroot

---

spec/temp-binding.test.sh

This commit adds a failing spec test to tickle a crash that happens when evaluating a simple command that is prefixed with variable bindings.

add spec test for #2411

---

osh/cmd_eval.py
spec/temp-binding.test.sh

We have a helper to check if prefix bindings should pe preserved when running a simple command. This check requires checking the first argument of the command line, but doesn't check the length before indexing. This commit patches the helper to return early if argv is empty. From there, the usual command execution logic will take care of the rest: either a noop, or erroring out if strict_argv is enabled.

check argv length before indexing (fixes #2411)

---

deps/source.medo/bash/WEDGE
deps/source.medo/python2/WEDGE

I also ran into issue #2312 on my arch installation. It seems like newer compilers have a conflict with the source code that is defining its own `true` and `false` (the issue has a more detailed explanation). Forcing an older C standard when building seems to resolve the issue.
The compiler on my system is `gcc (GCC) 15.1.1 20250425`

fix python2 build with newer compilers

---

deps/source.medo/bash/WEDGE
deps/source.medo/busybox/WEDGE
deps/source.medo/zsh/WEDGE

Fixed some small issues with building dependencies, which seem to no longer build when using gcc >= 14 (in the case of bash and zsh) or when using linux kernel >= 6.8 (busybox).
For busybox the recommended workaround was just disabling the module.
For bash and zsh the fix was treating certain compile errors as warnings (which was the default behavior for those errors before gcc 14). So I think these changes should also not really have an impact on existing working environments with an older gcc.
For reference here were the compilation issues:
zsh: `termcap.c:45:14: error: conflicting types for ‘boolcodes’; have ‘char *[]’`
busybox: `tc.c:296:24: error: invalid use of undefined type ‘struct tc_cbq_lssopt’`
bash: `parse.y:5741:21: error: implicit declaration of function ‘count_all_jobs’ …

Deps build errors

---

mycpp/NINJA_subgraph.py
mycpp/datalog/dataflow.dl
mycpp/examples/gc_stack_roots.py
mycpp/mycpp_main.py
prebuilt/datalog/dataflow.cc

The pretty printer found a gap in the stack roots optimizer. It was
falling over on code with the following form:
x = alloc_something()...
do_something(x, function_that_collects())
We werent' generating a root for `x` because its use isn't captured by
the live variable analysis. This commit adds a rule to the rooting
policy to capture this case and adds an example that we can use to check
for regressions.

mycpp: fix seg fault in pretty printer
